### ISSUE TITLE
[Suggestion] Loading pokemon locations from PokemonGo-Map database

### ISSUE THREAD

**Issue by Arderos** [PokemonGoF/PokemonGo-Bot#1043]
PokemonGo-Map project has an ability to store pokemon locations inside the mysql database. The format is as follows:
encounter_id | spawnpoint_id | pokemon_id | latitude | longitude | disappear_time

If the bot would optionally use this information to catch pokemons it would be a great improvement in leveling speed and overall effectiveness.

The bot logic could be like this:
1. Get bot location
2. Query database for pokemons
3. Find out which ones are within walking range before they disappear.
4. Plot a route
5. Cath'em all

**Comment by MikeDX** [comment]
I have been considering a custom navigator to do exactly this, since it can then be programmed to hunt pokemon you want, so if you have a good map database running with a decent scanning area, you can tell it to head for that area automatically when a pokemon you "need" is there. Could also be smarter and check your pokedex / bag to collect ones you do not yet have.

**Comment by justinbeatz** [comment]
+1

**Comment by surfaace** [comment]
for tracking purpose #861 #1250
