### ISSUE TITLE
Pokeball useage logic

### ISSUE THREAD

**Issue by TSM-EVO** [PokemonGoF/PokemonGo-Bot#116]
Logic for pokeball use, for example:

1.  Pokemon CP under 200, use Pokeball
2.  CP over 200 Use Greatball
3.  CP over 500 Use Ultraball

Or some kind of logic that uses Pokeballs first, then uses Great Balls

Would also be good to use this logic to use Berries later. 

Could also select Pokeballs first, then Greatballs, then Ultraballs as they run out.

**Comment by Mordana** [comment]
Noticed the same since last merge
Code seems to use Greatball regardless of CP and regular Pokeballs count ( > 0)
I have a couple dozen regulars in inventory but still nothing but Greatballs are used.
I'm not sure if it's related but in my case I do have more Greatballs than I have regulars.

Something rustles nearby!
A Wild Weedle appeared! [CP121]
Using Greatball...
Captured Weedle! [CP121]
A Wild Weedle appeared! [CP10]
Using Greatball...
Captured Weedle! [CP10] - exchanging for candy
Exchanged successfuly!
A Wild Pidgey appeared! [CP97]
Using Greatball...
Captured Pidgey! [CP97] - exchanging for candy
Exchanged successfuly!
A Wild Eevee appeared! [CP107]
Using Greatball...
Captured Eevee! [CP107]

**Comment by skydrome** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/cell_workers/pokemon_catch_worker.py#L38

if i change decrement the range by 1 to
`for i in range(-1,2):`
it works as it should again, tho i dont know why
