### ISSUE TITLE
The "AND" and "OR" release logic is reversed

### ISSUE THREAD

**Issue by LostDGod** [PokemonGoF/PokemonGo-Bot#1169]
OR
CP		IV
ABOVE	ABOVE --> kept
ABOVE 	BELOW --> exchanged
BELOW 	ABOVE --> exchanged
BELOW 	BELOW --> exchanged

AND
CP		IV
ABOVE	ABOVE --> kept
ABOVE 	BELOW --> kept
BELOW 	ABOVE --> kept
BELOW 	BELOW --> exchanged

---OR---

#ABOVE ABOVE
 
 "release": {
    "any": {"release_below_cp": 200, "release_below_iv": 0.4, "logic": "or"},

 A Wild Zubat appeared! [CP 253] [Potential 0.47]
 IV [Stamina/Attack/Defense] = [8/10/3]
 Using Pokeball (chance: 37.43%)... (76 left!)
 Captured Zubat! [CP 253] [8/10/3]
                               ] 12%

#ABOVE BELOW 

"release": {
    "any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "or"},
	  
 A Wild Vaporeon appeared! [CP 1279] [Potential 0.38]
 IV [Stamina/Attack/Defense] = [2/15/0]
 Using Greatball (chance: 15.89%)... (25 left!)
 [-] Attempted to capture Vaporeon - failed.. trying again!
 Using Greatball (chance: 15.89%)... (24 left!)
 Captured Vaporeon! [CP 1279] [2/15/0]
 Vaporeon has been exchanged for candy!
 						   
#BELOW ABOVE

"release": {
    "any": {"release_below_cp": 1000, "release_below_iv": 0.1, "logic": "or"},
	
 A Wild Pidgeot appeared! [CP 359] [Potential 0.27]
 IV [Stamina/Attack/Defense] = [6/3/3]
 Using Greatball (chance: 20.69%)... (20 left!)
 Captured Pidgeot! [CP 359] [6/3/3]
 Pidgeot has been exchanged for candy!
						   
#BELOW BELOW
							   
 "release": {
    "any": {"release_below_cp": 200, "release_below_iv": 0.9, "logic": "or"},
	
 A Wild Jynx appeared! [CP 118] [Potential 0.51]
 IV [Stamina/Attack/Defense] = [3/14/6]
 Using Pokeball (chance: 55.62%)... (75 left!)
 Captured Jynx! [CP 118] [3/14/6]
 Jynx has been exchanged for candy!

---AND---

#ABOVE ABOVE
 
 "release": {
    "any": {"release_below_cp": 10, "release_below_iv": 0.1, "logic": "and"},

 A Wild Beedrill appeared! [CP 131] [Potential 0.4]
 IV [Stamina/Attack/Defense] = [9/1/8]
 Using Greatball (chance: 27.84%)... (19 left!)
 [-] Attempted to capture Beedrill - failed.. trying again!
 Using Greatball (chance: 27.84%)... (18 left!)
 Captured Beedrill! [CP 131] [9/1/8]
 Found fort 86ec1d4df8a94754b1db9341bd6de6b4.16 at distance 0.04km
	
#ABOVE BELOW
 
 "release": {
    "any": {"release_below_cp": 400, "release_below_iv": 0.9, "logic": "and"},

 A Wild Clefairy appeared! [CP 502] [Potential 0.33]
 IV [Stamina/Attack/Defense] = [1/5/9]
 Using Greatball (chance: 30.83%)... (22 left!)
 Captured Clefairy! [CP 502] [1/5/9]
 Found fort 9260eb542a0c492484e645d055a8a821.16 at distance 0.03km
 
#BELOW ABOVE

 "release": {
    "any": {"release_below_cp": 1000, "release_below_iv": 0.1, "logic": "and"},

 A Wild Ekans appeared! [CP 475] [Potential 0.42]
 IV [Stamina/Attack/Defense] = [9/2/8]
 Using Greatball (chance: 42.14%)... (17 left!)
 Captured Ekans! [CP 475] [9/2/8]
 Found fort 86ec1d4df8a94754b1db9341bd6de6b4.16 at distance 0.04km
 
#BELOW BELOW

 "release": {
    "any": {"release_below_cp": 1000, "release_below_iv": 0.9, "logic": "and"},
	
 A Wild Bulbasaur appeared! [CP 594] [Potential 0.4]
 IV [Stamina/Attack/Defense] = [5/0/13]
 Using Greatball (chance: 18.13%)... (16 left!)
 [-] Attempted to capture Bulbasaur - failed.. trying again!
 Using Greatball (chance: 18.13%)... (15 left!)
 Captured Bulbasaur! [CP 594] [5/0/13]
 Bulbasaur has been exchanged for candy!

**Comment by gpires** [comment]
Maybe its related to this commit: 7aaf3458b6b20011cda86ad434f0a88793b92ef9

**Comment by crusardri** [comment]
i downloaded the last commit and the bot catch and not release a pidgey CP 100 IV 0.4
 "Pidgey": { "release_below_cp": 237, "release_below_iv": 0.8, "logic": "or" },

**Comment by VictorChen** [comment]
the logic seems fine to me?

```
"any": {"release_below_cp": 200, "release_below_iv": 0.4, "logic": "or"}
```

this is saying it will release the pokemon if the cp is below 200 OR if the iv is below 0.4

for your first example:

```
A Wild Zubat appeared! [CP 253] [Potential 0.47]
IV [Stamina/Attack/Defense] = [8/10/3]
Using Pokeball (chance: 37.43%)... (76 left!)
Captured Zubat! [CP 253] [8/10/3]
] 12%
```

```
cp below 200? => no
iv below 0.4? => no
don't release pokemon
```

**Comment by Foulwerp** [comment]
I think "or" works fine its "and" that is broken. It only checks one parameter instead of both.  Look at the and with Clefairy.
`(cp below 400? -> false
iv below 0.9 -> true) ->
don't release pokemon (incorrect)`

When using "and" both should have to be above to not release.  In this case the CP is above but the IV is below meaning it should be released not kept. If it was "or" it would be working correctly, but it is not.

**Comment by VictorChen** [comment]
@Foulwerp how is that wrong?

It releases Clefairy ONLY if its cp is below 400 AND iv is below 0.9

since its cp is not below 400, it will not release.

**Comment by Foulwerp** [comment]
Logically AND would mean both have to pass the check to be kept. 

Since the IV is below the threshold it should release it, but doesn't. 

Your example right now would be an OR. With OR logically only one has to pass the check, this one passed OR this one passed kept it. While again with and BOTH have to pass to be.

AND
Both have to pass, be above the threshold, to be kept.

OR
Only one has to pass, be above the threshold, to be kept.

**Comment by crusardri** [comment]
i copy-paste my old config (release_config.json) and don't work fine (i remplace "under" to "below" and fix other changes made in the lastest commits)

Sorry for my bad english

**Comment by VictorChen** [comment]
@crusardri try using this config: https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/configs/config.json.pokemons.example

**Comment by crusardri** [comment]
@VictorChen i try this config and don't work as i expected, catch all pokemon and don't release anyone.
This is my config.
http://pastebin.com/ha6gWiWy
i think is all right

**Comment by douglascamata** [comment]
@LostDGod with the config file you provided, you will release anything below CP 1000 and IV 0.9, which is equivalent to releasing 99% of the pokemon you find.

**Comment by Shoh** [comment]
I think this can be closed as it's a misunderstanding of the logic. The logic is correct and your first example shows it.  Using your example, the logic is doing the following:

OR (only one condition needs to equate to true in order to result in a true value)
CP IV
ABOVE ABOVE --> kept
CP below threshold? false  ||  IV below threshold? false  -> keep (false || false == false)

ABOVE BELOW --> exchanged
CP below threshold? false  ||  IV below threshold? true -> exchange  (false || true == true)

BELOW ABOVE --> exchanged
CP below threshold? true -> exchange (true || false == true)
(no need to check the 2nd condition because it's an OR and only one condition needs to equate to true in order to result in a true value)

BELOW BELOW --> exchanged
CP below threshold? true -> exchange (true || true == true)
(no need to check the 2nd condition because it's an OR and it's already true)

AND (both conditions must equate to true in order to result in a true value)
CP IV
ABOVE ABOVE --> kept
CP below threshold? false  &&  IV below threshold? false -> keep (false && false == false)

ABOVE BELOW --> kept
CP below threshold? false && IV below threshold? true -> keep (false && true == false)

BELOW ABOVE --> kept
CP below threshold? true && IV below threshold? false -> keep (true && false == false)

BELOW BELOW --> exchanged
CP below threshold? true && IV below threshold? true -> exchange (true && true == true)
(both conditions equate to true so the result is true and the pokemon is released)

**Comment by douglascamata** [comment]
It's boolean math. If it returns `True`, it works as expected. There has been a lot of discussion about it already. The code is also VERY straightforward (I implemented it myself to ensure clean code).
