### ISSUE TITLE
Using greatballs for every pokemon

### ISSUE THREAD

**Issue by harsh1412** [PokemonGoF/PokemonGo-Bot#119]
[#] Finished walking to (xx)
(xx)
[#] Something rustles nearby!
[#] A Wild Doduo appeared! [CP11]
[x] Using Greatball...
[x] Captured Doduo! [CP11] - exchanging for candy
I have like 217 Normal pokeballs -.-'

**Comment by TheGoldenXY** [comment]
Feature not implemented yet.

**Comment by harsh1412** [comment]
@TheGoldenXY I mean its using greatballs for every pokemon.

**Comment by hvdklauw** [comment]
The issue is here: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/cell_workers/pokemon_catch_worker.py#L38

It loops through the items and uses the last one found.

To switch to normal pokeballs before greatballs (and ultraballs/masterballs) you need to change the range function to this:
```python
for i in range(4, 0, -1):
```

That will loop through it in reverse.

**Comment by Balauue** [comment]
I suggest a blacklist to not catch the most common Pokemon (as defined by a list) using gread balls / master balls / ultra balls.

This list can also be used to get automatically get rid of these Pokemon, regardless of CP.

**Comment by surfaace** [comment]
it was fixed at some point in DEV branch
