### ISSUE TITLE
Bot doesn't find incubators?

### ISSUE THREAD

**Issue by Roydeking52** [PokemonGoF/PokemonGo-Bot#1251]
### Expected Behavior
That it does find incubators?

### Actual Behavior
It doesn't find any incubators.

I notice that the bot doesn't find incubator. I saw somebody on level 20 with 5 incubator and i have only the stock one. It doesn't find incubator at pokestops.

**Comment by astose** [comment]
Incubators do not come out from Pokestops. Only eggs do.

If you want an incubator, you have to acquire certain level on which one is provided to you.

**Comment by Nurvx** [comment]
Leveling up gives you incubators, or buying them.

**Comment by Roydeking52** [comment]
I have 1 incubator and im level 18.

**Comment by Nurvx** [comment]
@Roydeking52  Go [here](http://www.ign.com/wikis/pokemon-go/Level_Rewards_and_Unlockable_Items).

**Comment by Roydeking52** [comment]
aah oke i get it now thx for the link.

**Comment by davericher** [comment]
Close issues if solved...

**Comment by Roydeking52** [comment]
how?

**Comment by Whosdaman** [comment]
The button to the immediate left of the "Comment" button. It says "Close Issue"

**Comment by silelmot** [comment]
How is this solved? I also dont get incubators... Level 16 should have 3

**Comment by Nurvx** [comment]
This is closed because Pokestops do not give Incubators. You get Incubators from leveling and/or buying from shop. Now, if you have leveled while suing the bot and you do not have items received from leveling, that is a different story. Personally I haven't had an issue, every time I have leveled I logged into the game after using the bot and I get the level up notification with my items.

**Comment by silelmot** [comment]
Ok. I see. Thx. 
So its a different Problem, that the bot doesnt collect the items from levelling
