### ISSUE TITLE
catch_ignore feature on dev

### ISSUE THREAD

**Issue by Philipp59** [PokemonGoF/PokemonGo-Bot#1501]
can we get a ignore feature on dev like on the master with catch_ignore.yml ?

[00:10:50] A Wild Meowth appeared! [CP 70] [Potential 0.53]
[00:10:50] IV [Stamina/Attack/Defense] = [13/11/0]
[00:10:57] Something rustles nearby!
[00:10:57] A Wild Meowth appeared! [CP 70] [Potential 0.53]
[00:10:57] IV [Stamina/Attack/Defense] = [13/11/0]
[00:11:05] Something rustles nearby!
[00:11:05] A Wild Meowth appeared! [CP 70] [Potential 0.53]
[00:11:05] IV [Stamina/Attack/Defense] = [13/11/0]
[00:11:12] Something rustles nearby!
[00:11:13] A Wild Meowth appeared! [CP 70] [Potential 0.53]
[00:11:13] IV [Stamina/Attack/Defense] = [13/11/0]
[00:11:34] Something rustles nearby!

I have the feeling that this (1!) meowth is blocking other pokemons from being discovered by the bot.

**Comment by VictorChen** [comment]
Can you post your config?

**Comment by Philipp59** [comment]
"any": {"catch_above_cp": 0, "catch_above_iv": 0, "logic": "or"},
      "Meowth": {"never_catch": true}

tested also:
"Meowth": {"catch_above_cp": 999, "catch_above_iv": 0.99, "logic": "or"}

no difference at all, the bot is not catching like the config say, but there is a huge difference compared  to ignoring, with the old ignore_catch.yml on master the meowth not appeared for the bot

**Comment by glitchsnob** [comment]
Im experiencing the same issue I loved the old yml it they wouldnt even show up, tried the same never catch statement they still show and are caught as well

**Comment by AlexBailey** [comment]
@Philipp59 Apologies for skewing this off topic - I noticed your wiki entry of applescript to open restart the bot. I was wondering if you'd be able to publish an applescript to restart the bot after X amount of time so that you can leave the bot unattended throughout the day and this will iron out any crashes throughout the day ensuring the bot's uptime is close to 100%. I've been trying to develop this script myself, but no luck unfortunately and you seem by far more comfortable with AppleScript than I am - if you could implement such a script on the wiki, I myself would be grateful and I believe then entire OSX community would be too! Again, sorry for digressing off thread topic, just no other means of contact for you. Thanks!
