### ISSUE TITLE
Bot Ignore given location - Bug

### ISSUE THREAD

**Issue by DimaVIII** [PokemonGoF/PokemonGo-Bot#1656]
### Expected Behavior
Jump to the location and not start from Last location flag.

If you push the location through ./pokecli.py -l "40.XXX,-73.XXXX" it should ignore location_cache.

### Actual Behavior
Bot is not Jumping to the given location. It always start at Last location flag.

Not with CLI: 
./pokecli.py -l "40.XXX,-73.XXXX"
and also not over config.json

### LOG
[17:34:22] PokemonGO Bot v1.0
[17:34:22] Configuration initialized
[17:34:22] [x] Coordinates found in passed in location, not geocoding.
[17:34:22] 
[17:34:22] Location Found: 40.765840,-73.973439
[17:34:22] GeoPosition: (40.76584, -73.973439, 0)
[17:34:22] 
[17:34:22] [x] Parsing cached location...
[17:34:22] 
[17:34:22] [x] Last location flag used. Overriding passed in location
[17:34:22] [x] Last in-game location was set as: (40.764554398120005, -73.97592064488613, 0)
[17:34:22] 
[17:34:22] Attempting login to Pokemon Go.
[17:34:24] Login to Pokemon Go successful.

### CONFIG.json
    "max_steps": 5,
    "catch_pokemon": true,
    "forts": {
      "spin": true,
      "avoid_circles": true,
      "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": 12.28,
    "action_wait_min": 1,
    "action_wait_max": 3,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "km",
    "reconnecting_timeout": 15,
    "item_filter": {
      "1": { "keep" : 20 },
      "2": { "keep" : 150 },
      "3": { "keep" : 200 },
      "101": { "keep" : 1 },
      "102": { "keep" : 100 },
      "103": { "keep" : 250 },
      "201": { "keep" : 30 },
      "701": { "keep" : 50 }
    },
    "evolve_all": "all",
    "evolve_speed": 6.5,
    "evolve_cp_min": 10,
    "use_lucky_egg": false,
    "hatch_eggs": true,
    "longer_eggs_first": true,
    "evolve_captured": false,
    "release_pokemon": true,

### Other Information
OS: OSx
Git Commit: be9e7bb79de33a7d177014184c510b2c60513be8

**Comment by zjr8** [comment]
set "location_cache": true to false and try

**Comment by xorinzor** [comment]
you need to change `cache_location` to `false` please read the documentation.

**Comment by DimaVIII** [comment]
If you push the location through ./pokecli.py -l "40.XXX,-73.XXXX" it should ignore location_cache.

**Comment by xorinzor** [comment]
No it shouldn't because that would make the bot teleport everytime you ran it.

You can't expect the bot to implement some kind of function to check the distance between the last location and the provided start location to determine whether it should teleport or not.

It's a bot, not a GUI for you to manually play.

**Comment by CapCap** [comment]
CLI should ABSOLUTELY override ANYTHING in the config file- it's silly to think it should ever work any other way. This discussion has been had multiple times: **CLI should always override config**.

Location cache shouldn't teleport you over speed*time distances Anyway, and passing location as CLI should, without smarter logic, at least reset the cache and rebuild around your nearest point (i.e if loc is always passed in, it's session-only loc cache)

> please read the documentation.

ok, sure. Oh wait-

Here is the documentation in master for it:
```
location_cache :
```

Here it is in dev:
```
```

**Comment by xorinzor** [comment]
Not sure where you're looking but clearly not in the right place. 

https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files

![screenshot 5](https://cloud.githubusercontent.com/assets/4212335/17256691/e9e60a42-55be-11e6-8e40-60a1c4b831fd.png)

CLI does override the property, however, the config still says to use the latest location so you'd have to override that in the CLI too.

I don't understand why this should be such a big deal, if he wants the bot to teleport just set it to `false`, done.

**Comment by Antairez** [comment]
During previous builds you need to clear location in order for location_cache to work, which is an annoying thing because who is gonna remember xx.xxxxxx,yy.yyyyyy anyway? I guess that's why it is done in this way.

Now the correct procedure would be continue to ignore location in config, but override location_cache when location is passed in from CLI, when location_cache is true.

**Comment by DimaVIII** [comment]
@CapCap calm down xD 
**CLI should always override config.** 100% true and that's the issue i'm trying to report!

@xorinzor 
"No it shouldn't because that would make the bot teleport everytime you ran it."
My opinion to this is: IF YOU ARE TO STUPID TO USE THE BOT AND GET SOFT BANNED... PLAY FAIR!

**Comment by xorinzor** [comment]
@DimaVIII so now you've ended up calling me stupid? dude, you have 1 repository and it's empty. I think it's fair to say you have little to no programming knowledge, now please have a look at mine.

This is a bot. If you were to run the config via CLI instead of passing it in a file it should use the provided location as a `default` value instead of an overrided value.

This way, if you have a watchdog making sure the bot doesn't crash, it will just continue where it left off.

Now stop making this a big deal and just change the config option.

**Comment by CapCap** [comment]
@xorinzor
![image](https://cloud.githubusercontent.com/assets/1482859/17256910/7088ab9a-5574-11e6-9821-139b66f57640.png)
On the main page, that's where I'm seeing that - which is a separate issue; either have config on there, or on the configs page, not randomly on both

Bot should never teleport faster than speed*time if it knows current_location and next_waypoint; if it's booting up and cache_location is set + location is passed in CLI, it should either:
1. Confirm this with the user
2. Clear cache and start at given point

You can "teleport" just fine w/o any bans in real life- i.e flying

**Comment by xorinzor** [comment]
@CapCap the main page is the readme.md for the master branch, not the dev branch.

**Comment by CapCap** [comment]
@xorinzor I get that for your specific case you dont need it. But lets think about which option is more flexible and better for the overall project instead of what you want?

Not passing CLI: works exactly as it does now

Passing CLI: clears cache, treats it as a temporary override

simple, flexible.

**Comment by DimaVIII** [comment]
@xorinzor No, I was not calling you stupid dude.  I was trying to admin (hard) that there is no logic.
Somehow you build this logic as a workaround for the watchdog. Ok now i understand why.

By the way my github profile isn't active. I'm programming not public.

**Comment by xorinzor** [comment]
@CapCap I guess what you're saying is true, and I was thinking about the overall project by the way.

I was just seeing it as something which could've been a lot simpler.

**Comment by CapCap** [comment]
@xorinzor the most painful part of cs is the easier it is for the user, the harder it usually is for the dev :-P

**Comment by gregtampa** [comment]
come to slack chat #help and someone can help you
NOT A BUG
