### ISSUE TITLE
KeyError: 'player_data'

### ISSUE THREAD

**Issue by aditardy** [PokemonGoF/PokemonGo-Bot#175]
i try login from mobile phone no problem... 

2016-07-22 18:53:38,233 [auth_google] [ INFO] Google Login successful.
2016-07-22 18:53:38,237 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-22 18:53:38,757 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-22 18:53:38,763 [    pgoapi] [ INFO] Login process completed
Traceback (most recent call last):
  File "C:\Python27\PokemonGo-Bot-master\pokecli.py", line 120, in <module>
    main()
  File "C:\Python27\PokemonGo-Bot-master\pokecli.py", line 114, in main
    bot.start()
  File "C:\Python27\PokemonGo-Bot-master\bot.py", line 24, in start
    self._setup_api()
  File "C:\Python27\PokemonGo-Bot-master\bot.py", line 155, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

**Comment by HT395925N** [comment]
I have the same issue.

**Comment by Imbos** [comment]
this could be a wrong version of pgoapi

pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi fixed it for me

**Comment by CtrlAltDefeat94** [comment]
Same problem here

**Comment by surfaace** [comment]
This is for dev branch, and it doesnt work with latest pgoapi

D:\Pokemon stuff\PokemonGo-Bot>pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git#egg=pgoapi
  Updating d:\pokemon stuff\pokemongo-bot\src\pgoapi clone
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in c:\python27\lib\site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0a3 in c:\python27\lib\site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in c:\python27\lib\site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in c:\python27\lib\site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in c:\python27\lib\site-packages (from pgoapi)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in c:\python27\lib\site-packages (from protobuf>=3.0.0a3->pgoapi)
Requirement already satisfied (use --upgrade to upgrade): setuptools in c:\python27\lib\site-packages (from protobuf>=3.0.0a3->pgoapi)
Requirement already satisfied (use --upgrade to upgrade): future in c:\python27\lib\site-packages (from s2sphere==0.2.4->pgoapi)
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->pgoapi)
Installing collected packages: pgoapi
  Running setup.py develop for pgoapi
Successfully installed pgoapi-1.1.0

**Comment by aTadTasty** [comment]
strange for osx it has some issues uninstalling the old version of protobuf.

`Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-SmH82a-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

**Comment by aditardy** [comment]
sloved.
remove all ...  
just install new all data

**Comment by surfaace** [comment]
define "remove all"

**Comment by aTadTasty** [comment]
pip uninstall protobuf 
And then 
pip install protobuf==3.0.0b3

doesn't seem to work for me

**Comment by Roydeking52** [comment]
i tried it still getting the same error

**Comment by aTadTasty** [comment]
anyone know what is this six-1.4.1?

`Root:PokemonGo-Bot-master copy aTadTasty$ pip install -r ./requirements.txt
Obtaining pgoapi from git+git://github.com/tejado/pgoapi.git@1f25e907f3e5f1b603330e71041e1ad7bee7580f#egg=pgoapi (from -r ./requirements.txt (line 1))
  Skipping because already up-to-date.
Requirement already satisfied (use --upgrade to upgrade): geopy==1.11.0 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 2))
Collecting protobuf==3.0.0b4 (from -r ./requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): s2sphere==0.2.4 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): gpsoauth==0.3.0 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 6))
Requirement already satisfied (use --upgrade to upgrade): protobuf-to-dict==0.1.0 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): googlemaps==2.4.4 in /Library/Python/2.7/site-packages (from -r ./requirements.txt (line 8))
Collecting six>=1.9 (from protobuf==3.0.0b4->-r ./requirements.txt (line 3))
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==3.0.0b4->-r ./requirements.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): future in /Library/Python/2.7/site-packages (from s2sphere==0.2.4->-r ./requirements.txt (line 5))
Requirement already satisfied (use --upgrade to upgrade): pycryptodomex>=3.0 in /Library/Python/2.7/site-packages (from gpsoauth==0.3.0->-r ./requirements.txt (line 6))
Installing collected packages: six, protobuf, pgoapi
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/vw/xtg9j2jx5wb1wjq77xyqz__m0000gn/T/pip-4TSIvC-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

**Comment by aditardy** [comment]
@Roydeking52  me to ... 
just remove all data and reinstall ...  work normaly run from my mac

**Comment by Roydeking52** [comment]
What data? can you expain, im using linux btw.

**Comment by aditardy** [comment]
y.. i copy new from git repo clone..

**Comment by Roydeking52** [comment]
yes me to

**Comment by surfaace** [comment]
worked in dev enviorment?

**Comment by aditardy** [comment]
work ...  need capture ? :D

**Comment by seadog007** [comment]
Some problem, too

**Comment by jtdroste** [comment]
Have you tried running `pip install -r requirements.txt`?  We updated some of the project's requirements recently

**Comment by Roydeking52** [comment]
yes everything i up to date

**Comment by surfaace** [comment]
D:\Pokemon stuff\PokemonGo-Bot>pip uninstall -r requirements.txt -y
Uninstalling geopy-1.11.0:
  Successfully uninstalled geopy-1.11.0
Uninstalling protobuf-2.6.1:
  Successfully uninstalled protobuf-2.6.1
Uninstalling requests-2.10.0:
  Successfully uninstalled requests-2.10.0
Uninstalling s2sphere-0.2.4:
  Successfully uninstalled s2sphere-0.2.4
Uninstalling gpsoauth-0.3.0:
  Successfully uninstalled gpsoauth-0.3.0
Uninstalling protobuf-to-dict-0.1.0:
  Successfully uninstalled protobuf-to-dict-0.1.0
Uninstalling googlemaps-2.4.4:
  Successfully uninstalled googlemaps-2.4.4

D:\Pokemon stuff\PokemonGo-Bot>pip install --upgrade -r requirements.txt --no-cache
Collecting geopy==1.11.0 (from -r requirements.txt (line 1))
  Downloading geopy-1.11.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 1.1MB/s
Collecting protobuf==2.6.1 (from -r requirements.txt (line 2))
  Downloading protobuf-2.6.1.tar.gz (188kB)
    100% |################################| 194kB 1.9MB/s
Collecting requests==2.10.0 (from -r requirements.txt (line 3))
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |################################| 512kB 5.7MB/s
Collecting s2sphere==0.2.4 (from -r requirements.txt (line 4))
  Downloading s2sphere-0.2.4-py2.py3-none-any.whl
Collecting gpsoauth==0.3.0 (from -r requirements.txt (line 5))
  Downloading gpsoauth-0.3.0.tar.gz
Collecting protobuf-to-dict==0.1.0 (from -r requirements.txt (line 6))
  Downloading protobuf-to-dict-0.1.0.tar.gz
Collecting googlemaps==2.4.4 (from -r requirements.txt (line 7))
  Downloading googlemaps-2.4.4-py2-none-any.whl
Requirement already up-to-date: setuptools in c:\python27\lib\site-packages (from protobuf==2.6.1->-r requirements.txt (line 2))
Requirement already up-to-date: future in c:\python27\lib\site-packages (from s2sphere==0.2.4->-r requirements.txt (line 4))
Requirement already up-to-date: pycryptodomex>=3.0 in c:\python27\lib\site-packages (from gpsoauth==0.3.0->-r requirements.txt (line 5))
Installing collected packages: geopy, protobuf, requests, s2sphere, gpsoauth, protobuf-to-dict, googlemaps
  Running setup.py install for protobuf ... done
  Running setup.py install for gpsoauth ... done
  Running setup.py install for protobuf-to-dict ... done
Successfully installed geopy-1.11.0 googlemaps-2.4.4 gpsoauth-0.3.0 protobuf-2.6.1 protobuf-to-dict-0.1.0 requests-2.10.0 s2sphere-0.2.4


Then executing:
pokecli.py -a ptc -u U -p Pl 59.328569,18.064374 -w 4.16 -s -c 1
[92m[x] PokemonGO Bot v1.0[0m
[93m[x] Configuration initialized[0m

[x] Address found: 59.328569,18.064374
[x] Position in-game set as: (59.3286798, 18.0644109, 0.0)

Traceback (most recent call last):
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 107, in <module>
    main()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokecli.py", line 99, in main
    bot.start()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 26, in start
    self._setup_api()
  File "D:\Pokemon stuff\PokemonGo-Bot\pokemongo_bot\__init__.py", line 160, in _setup_api
    player = response_dict['responses']['GET_PLAYER']['player_data']
KeyError: 'player_data'

**Comment by surfaace** [comment]
os: win10 pro n x64
launched from cmd

**Comment by aditardy** [comment]
try dell u folder data , redownload new and replace

**Comment by Roydeking52** [comment]
it worked :O thx

**Comment by surfaace** [comment]
Worked here too
