### ISSUE TITLE
[dev]  Improvment in the Task manager using threading libary

### ISSUE THREAD

**Issue by martijnvandijke** [PokemonGoF/PokemonGo-Bot#2034]
According to the documentation from the tasks https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files is it not far better and more efficient to thread this using the threading  library.

My proposal is to thread the walk to the fort and by using the radius of catching Pokemon and the given speed the thread timer can be calculated. 

Will work on a pull request but i do not have much time this weekend, please let me know how else this can be improved.

**Comment by TheSavior** [comment]
I believe we actually don't want this to be multi threaded. Each task has the ability to short circuit the tasks after it. For example, we want to let people configure the bot to catch all the pokemon around them before moving to the next fort. Otherwise we end up walking away from pokemon in order to go walk around the map.

The approach we are taking is that of a behavior tree. One of the other thins that will let us support are more complicated tasks that have sub tasks which run following a similar approach. Take a look at this for more context: https://github.com/PokemonGoF/PokemonGo-Bot/issues/142

Also, we are rate limited by the api and thus only make 2 requests per second. We actually wouldn't be that much better off parallelizing these tasks. Currently we are limited by the api, not cpu time.

**Comment by martijnvandijke** [comment]
Sounds like reasonable (and stupid of me)  maybe post this in the wiki ?

**Comment by TheSavior** [comment]
Thanks, added more info to https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files#configuring-tasks
