### ISSUE TITLE
Bot seems to not see any pokemon after a while

### ISSUE THREAD

**Issue by Marco208** [PokemonGoF/PokemonGo-Bot#2155]
https://www.reddit.com/r/pokemongobotting/comments/4vftw9/if_your_bot_has_stopped_catching_pokemon_its/

Is there a fix implemented yet?

**Comment by DayBr3ak** [comment]
I think throttling is already implemented.

**Comment by toremielck** [comment]
How do i apply throttling?

**Comment by Marco208** [comment]
Can someone confirm?

**Comment by reddivision** [comment]
for what it's worth, I noticed this a long time ago, and it was just because my bot had wandered into a place with few spawns, even though it started in a very populated location. but to answer the other points made, yes, there is some throttling implemented, and 5 second throttling for pokemon checks are coming soon.
