### ISSUE TITLE
"has been exchanged for candy"

### ISSUE THREAD

**Issue by Bomberj** [PokemonGoF/PokemonGo-Bot#2168]
![captura](https://cloud.githubusercontent.com/assets/20762268/17281174/7ef197d2-579a-11e6-979f-748dd94db4fd.PNG)
### Other Information
OS: windows
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by MrCarlosJr** [comment]
Your config exchange low cp pokemons. Try change config.json

**Comment by leovarmak** [comment]
@Bomberj Well this is because of the data in your configuration files. Are you on `Master `or `Dev `?
If you are in master, in your `PokemonGo-Bot` folder you will see a file called `release_config.json`. It has all the data regarding the pokemons release. So if a Pokemon meets the criteria of either `CP `or `IV`, that pokemon will be released.
