### ISSUE TITLE
Feature-Request: Discard items only if Bag is full

### ISSUE THREAD

**Issue by Ced4** [PokemonGoF/PokemonGo-Bot#2207]
Discard the items only if the Bag is full and not after every loot. This would be better in two ways:

- more human-like behavior - nobody would discard 1 item after every loot
- if you have set a maximum of 100 of each balls, the bot discards the pokeballs even if there is enough space in the bag. this is a waste of resources, you might need these balls until your bag is actually full.

What do you think?

**Comment by sgitkene** [comment]
To expand on this, I'd also propose keeping a priority list. When bag is full, throw away potions first, then revives, weakest balls and so forth as to maximize bag utility for the task one gives to the bot. For example potions are really useless for the bot and I keep them out of the inventory by keeping exactly 0 of echa kind, same with revives. but it sometimes throws away ultraballs because of the limit of 120 I set on them, but I'd rather have it throw away pokeballs, because they're so abundant.

**Comment by HecticSeptic** [comment]
#2219 
Oops, dupe, seems my search didn't pick up this item. +1
Note mine has additional suggestions/comments for consideration

**Comment by yahwes** [comment]
I changed this in my fork in [seen_fort_worker.py](https://github.com/yahwes/PokemonGo-Bot/commit/766123c02117d4f5d6daf41b9ee1c96b2cd6099a?diff=unified#diff-81044be212df0c715eb210253ab6d4eb)
