### ISSUE TITLE
[13:23:59]  Server seems to be busy or offline - try again - 1/5

### ISSUE THREAD

**Issue by pokecunt** [PokemonGoF/PokemonGo-Bot#2223]
```
[13:23:59]  Server seems to be busy or offline - try again - 1/5
[13:23:59]  Server seems to be busy or offline - try again - 1/5
[13:23:59]  Server seems to be busy or offline - try again - 1/5
[13:23:59]  Server seems to be busy or offline - try again - 1/5
[13:23:59]  Server seems to be busy or offline - try again - 1/5
```

**Comment by xorinzor** [comment]
Please next plain improve your issue with details.
Also check for existing issues first.

Duplicate: #2057

**Comment by pokecunt** [comment]
Pokemon Go is working on my phone.

This is a bot issue, not a Pokemon Go issue, as the error makes you believe.

Fix it.

**Comment by xorinzor** [comment]
I never said this wasn't a bot issue, and `Fix it.`? really?

If I was a developer working on the bot I'd be severely pissed at you right now for just commanding something to be fixed.

**Comment by MFizz** [comment]
Well, his name **is** pokecunt... :D

**Comment by xorinzor** [comment]
@MFizz no reason to act like that though, it's open-source and free software, don't like it, don't use it >.<

I get really pissed off when people act like we (developers in general) are just their personal workers.

**Comment by pokecunt** [comment]
s/open-source and free software/broken software.

No wonder things keep breaking, with 12 year olds getting pull requests merged every 5 minutes.

**Comment by xorinzor** [comment]
@pokecunt again, if you don't like it, don't use it. Nobody is forcing you to.

Certainly insulting the people who work on this project and invest their free time into it isn't going to help.

**Comment by avallete** [comment]
@pokecunt why not investigate on this issue and fixing it instead of be a douche bag with everyone ?
It's because of people like you than open-sourced and free software are so hard to maintain.
So why you don't go kick your poor dog like you usually do for expulse your frustration. For letting people who actually work on this project and who trying to maintain it free and efficient do the best ?

@xorinzor I have experimented the same issue. After a little investigation it's seem to come from the new pgoapi requirement version.
### Test Procedure
I tried login with version:
`git+https://github.com/tejado/pgoapi.git@bfa96ba6a746b5be17d8c9137514f1758138b234#egg=pgoapi`

And all work fine on previous version (commit: `32cefeed4760d6b5d2b3eb76d783d0f13d068e83`) . But when I switch to the current requirement version:
` git+https://github.com/tejado/pgoapi.git@81e786cabf027a1c8fbd1e9a07e1c11aa3d8ee8b#egg=pgoapi`

And the current commit. I've got an NoLoggedInException.

I've also try to just revert the requirement version but it seem the current version ('dev branch') use some new feature of this api version (like `get_cell_ids` in `pokemongo_bot/__init__`).

I will  try investigate deeper on this subject when I got some time (check commits on pgoapi and PokemonGo-Bot between working and unstable commit).

**Comment by MFizz** [comment]
Arguing here wont change his view. He clearly embraces his cuntiness if he's named like that. But I'm not running to work either, so just ignore.

**Comment by registered99** [comment]
I get the same thing, which is odd because it doesn't increment at all.

**Comment by pokecunt** [comment]
Switched to OpenPoGoBot, that project actually works and seems to have some sort of organisation unlike this piece of shit.

**Comment by xorinzor** [comment]
@pokecunt we won't miss you.

**Comment by pokecunt** [comment]
![18beum](https://cloud.githubusercontent.com/assets/20769107/17321253/81298424-588f-11e6-8d3a-e8f887b64582.jpg)

**Comment by iruy** [comment]
Looks like this guy is just an ass***e keeping spamming and posting useless things.. Don't lose your time after him, none of you is a babysitter :D
