### ISSUE TITLE
Egg Hatching Issues

### ISSUE THREAD

**Issue by Drambuie** [PokemonGoF/PokemonGo-Bot#2228]
### Expected Behavior

Bot should output details on what was hatched from egg

### Actual Behavior

[14:40:25]  ------------------------------ 
[14:40:25]  [!] Eggs hatched, but we had trouble with the response. Please check your inventory to find your new pokemon! 

### Steps to Reproduce

Latest Dev build

### Other Information
OS: Ubuntu
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by JohnKarel** [comment]
Confirmed, I have the same issue with the latest dev.

**Comment by vanrzuf** [comment]
Same here

**Comment by jokoast** [comment]
Does it incubate ? I have an issue like i connect on my phone and just see no egg in incubator ...

**Comment by reddivision** [comment]
This is an issue we're trying to sort out. We know that, according to Niantic, we've walked far enough to have the egg hatch, that's why the hatch code triggers, but they're sending us back a standard response with no details, so there's nothing we can possibly display. At this point, the error could be anywhere in the chain, but abnormal responses like this are historically indicative of an API discrepancy (i.e. we're out of date and need to update, or something of the sort).

**Comment by reddivision** [comment]
To answer your question @jokoast, yes, egg incubation still seems to be working fine. I've been getting the error message above for hatching as well, but, even logged into the app, I'm seeing the bot add new eggs and the walk distance on them increase as the bot works.

**Comment by tokarevi** [comment]
I have this issue, but the bot does not put new eggs into incubators.

**Comment by ChrisHaPunkt** [comment]
If u enable the renaming in config, u are able to get the name and iv from the hatched pkmn:

> [09:43:16]  [!] Eggs hatched, but we had trouble with the response. Please check your inventory to find your new pokemon!
[09:43:16]  [x] Now incubating a 5.0km egg
[09:43:19]  Nickname set successfully! Voltorb is now Voltorb91
