### ISSUE TITLE
why not to nearby pokestop?

### ISSUE THREAD

**Issue by winardiaris** [PokemonGoF/PokemonGo-Bot#2323]
how to walk to the nearest pokestop? configuration like what?

**Comment by xorinzor** [comment]
Did you read https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files ?

**Comment by Yutsa** [comment]
Is there a place where each task is detailled with all its options ? The wiki link doens't give a lot of information on tasks actually. My bot spends most of its time going from pokestop to pokestop and rarely catch pokemons even if I have the `CatchVisiblePokemon` and `CatchLuredPokemon` task on the list. Is it because it is "stuck" in the "MoveToFort" task?

**Comment by xorinzor** [comment]
@Yutsa The tasks names pretty much explain themselves, not every task has options and those that do are pretty well explained in my opinion?

if you have any other questions, just join our SLACK chat https://pokemongo-bot.slack.com/ in the #help channel
