### ISSUE TITLE
IV unclear

### ISSUE THREAD

**Issue by DokterPhill** [PokemonGoF/PokemonGo-Bot#2355]
### Expected Behavior
I've read through the IV explanation on the wiki, and some more on google and while i understand what it does, i dont know what would be an appropriate value to enter in the IV filter to filter out low IV's. Any help would be appreciated.

### Other Information
OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by Dunduro** [comment]
i believe the IV filter takes 0.00-1.00,

personaly i got mine set to 0.9 but you could add an extra digit if you want to be specific, since there are 45 values (15/15/15) step size is 1/45 so about 0.022 so if you want to filter for pokemon that are only missing 3 or less values you could set it to 0.93 and it wil toss a 41/45 would be 9.11111.

i hope that answers your question
