### ISSUE TITLE
pokemon go proxy 

### ISSUE THREAD

**Issue by ravdesai09** [PokemonGoF/PokemonGo-Bot#2502]
is there any software ,for pokemon go app for editing protocol  like like charles web proxy ?

**Comment by snei-klvs** [comment]
You can use mitm proxy. There's a node package for it [here](https://www.npmjs.com/package/pokemon-go-mitm) but with the latest client cert pinning is implemented so it won't work unless you use an older version.

**Comment by klvs** [comment]
You can use mitm proxy but in the latest client cert pinning is implemented so it won't work unless you're using an older version. https://www.npmjs.com/package/pokemon-go-mitm

**Comment by ravdesai09** [comment]
Thanks buddy but this thing is out of my box to understand ..  i am not that much technically .. just want to ask does it work on laptop i mean on windows ?????

**Comment by klvs** [comment]
Yeah it does. However, there are a lot of very technical barriers to overcome. Currently it won't work because of API changes. 

**Please close this issue.** It's not related to this project and this isn't the place to ask questions. When you open up unrelated or otherwise unhelpful issues on a repo it drowns out important issues and makes it much more difficult for the maintainers to fix legitimate issues.
