### ISSUE TITLE
Can someone explain to me how move_to_fort, follow_cluster, follow_path, follow_spiral work together?

### ISSUE THREAD

**Issue by TianCNCA** [PokemonGoF/PokemonGo-Bot#2504]
i.e., if I define them all in the config file, will they all work fine or they will conflict with each other? I believe it's the latter case as my bot kept stuck at one fort. If it's indeed the case then we should add checks to prevent the user from using them at the same time.

**Comment by rohimkudus** [comment]
same as mine, bot won't walk far so hatch egg slower, and where is Walk_Step not found in config?

**Comment by sgitkene** [comment]
they will conflict. I recommend you use only one.
the way it is supposed to work is that the bot goes through the tasks by priority (higher up means higher priority) and everytime it encounters a doable task it will start from top again. moving is almost always possible, so it will not reach anything below that task usually. it is nice to have a fallback at the end though, like spiral. but more than that is redundant.
like why would you have both a path and a spiral? or move to fort and follow cluster? but one of each is probably fine.
you can even have only move to fort, but then you need to make sure that you have not full inventory by a fair margin, otherwise it just stops.
