### ISSUE TITLE
Incense & Incubator Automation +more issues

### ISSUE THREAD

**Issue by NYF2** [PokemonGoF/PokemonGo-Bot#2580]
Noticed GoBot doesn't have an incense use option and can eyes automatically be placed in the incubator through the bot?

Issues I'm seeing:
-transferring pokemon in bulk happens in milliseconds. Can that be slowed down to prevent soft ban? Pretty big red flag if 50 pokemon are transferred in the time it takes a human to do 5. 

-every time bot is running, google sends a verification to my phone. It says "a change in google account requires check status"

**Comment by iruy** [comment]
For eggs there is the [`IncubateEggs` task](https://github.com/PokemonGoF/PokemonGo-Bot/wiki/Configuration-files). 
For pokemon transfer, when happens (used to) at bot start, it usually take 1-2 seconds for each pokemon..

**Comment by NYF2** [comment]
Okay I'll have to check that out. The auto transfer is fine. I'm talking about manual transfer. If I manually transfer in batches, bot will transfer each pokemon every millisecond. So 50 pokemon in 50 milliseconds. Doing it 1 by 1 is too slow when bot is picking up 2x as fast.

**Comment by BobbyWibowo** [comment]
I wasn't aware of this manual transfer. How did you do it? :hushed: 

Also, I can confirm the thing about "a change in Google account requires check or whatever" thingy. I used an App password for Pokemon-Go bot since I had two-step verification. But whenever the bot logins with my Google account, I'll be logged out from my phone and has to re-login. And to be honest, it was a pain since I had two-step verification as well..
