### ISSUE TITLE
noob installation ? windows

### ISSUE THREAD

**Issue by colmclovin** [PokemonGoF/PokemonGo-Bot#2606]
i have never used python as of prior to this, and the installation page is quite vague with have to install everything, anyone with enough time to produce a noob install guide would be greatly appreciated.

**Comment by Yakusari** [comment]
My installation:

Log in as root (otherwise use 'sudo' in front of the commands) for Ubuntu 16.04/14.04:

apt-get update

apt-get upgrade

apt-get install python-setuptools

apt-get install python-pip

apt-get install git

apt-get install virtualenv      (apt-get install python-virtualenv (for Ubuntu 14.04)

apt-get install python-protobuf

cd /opt/

git clone --recursive -b master https://github.com/PokemonGoF/PokemonGo-Bot

cd PokemonGo-Bot

virtualenv .

source bin/activate

pip install -r requirements.txt

cp /opt/PokemonGo-Bot/configs/config.json.example /opt/PokemonGo-Bot/configs/config.json

nano /opt/PokemonGo-Bot/configs/config.json (edit your config file [Ctrl +  O to save, Ctrl + X to exit])

python pokecli.py --config configs/config.json (to run the Bot)

**Comment by colmclovin** [comment]
Would be awesome if I used Linux

**Comment by Rlewisrlou666** [comment]
What Operating System are you running?

**Comment by ironbishop** [comment]
why in the world do you want to install a broken bot? RTFM #2540

**Comment by colmclovin** [comment]
Windows 10

**Comment by brantje** [comment]
Closing issue. Read #2540
