### ISSUE TITLE
Some doubts regarding using PokemonGo-Map with PokemonGo-Bot

### ISSUE THREAD

**Issue by zetasq** [PokemonGoF/PokemonGo-Bot#2845]
When spefifying **MoveToPokemonMap** field in **config.json**, I need to run a separate **PokemonGo-Map** app with another Google account.
So I have some doubts about the implementation of the **sniping mechanism**: Does **PokemonGo-Bot** app only search the fixed area whose location is set in **PokemonGo-Map** app? Or the **PokemonGo-Bot** app dynamically search the larger area surrounding the bot and make the search requests to the **PokemonGo-Map** app?

**Comment by BobbyWibowo** [comment]
It will only snipe Pokemon which was found by PokemonGo-Map. The update_map option may actually update the PokemonGo-Map location, but I'm not entirely sure whether it works or not.

**Comment by infeedel** [comment]
@zetasq The map scans a specific location which then passes on the data to the bot, and according to what you have set in the "MoveToPokemonMap" task, it will try and catch the pokemons you have specified (which is by default all pokemon I think)

PokemonGo-Map also has a web frontend with a map where you can change the location if you found coords for a specific pokemon for example

@BobbyWibowo the update_map option updates the map with the coords set in "location" from the bot, i personally don't use that option

**Comment by zetasq** [comment]
@infeedel So the update_map option did update the location, thanks :) 
By the way, I use the Electron version of PokemonGo-Map, but the map just never moves. Do you have the same problem? Maybe it's a bug with PokemonGo-Map :(

**Comment by BobbyWibowo** [comment]
@zetasq It seem to update PokemonGo-Map position only when the bot is 500m away from the PokemonGo-Map's center point and it has been at least 2 minutes since the last update. I may be wrong though, but it's supposed to log `Updated PokemonGo-Map position` into the bot console when it do that and I haven't seen that message till now.
To be fair, it seems my bots don't walk more than 100m from their starting point. I'm assuming it's because their location is full of lured PokeStops (gg american museum natural history) and it will only snipe Pokemon from the map (thus they'll always teleport back to their previous location).

**Comment by zetasq** [comment]
@BobbyWibowo Thanks :) I just hope the PokemonGo-Bot can integrate with PokemonGo-Map more closely. I can see the log of `Updated PokemonGo-Map`. But does PokemonGo-Map log that location is updated by PokemonGo-Bot? The Electron interface of PokemonGo-Map seems never move the location.

**Comment by BobbyWibowo** [comment]
> But does PokemonGo-Map log that location is updated by PokemonGo-Bot?

I have no idea, to be honest.
