### ISSUE TITLE
WebSocket implementation for actions menu (Feature)

### ISSUE THREAD

**Issue by phattrent** [PokemonGoF/PokemonGo-Bot#2897]
### Expected Behavior
Actions menu for web (evolve/release) should work.

### Actual Behavior
Currently OpenPoGoBot is the only one that supports OpenPoGoWeb actions menu for evolve/release.

### Steps to Reproduce
Run the simple server, you will see this in the logs.
"GET /socket.io/?EIO=3&transport=polling&t=LPcBNSj HTTP/1.1" 404 -

### Other Information
This is a really nice feature is someone working on this?
https://github.com/OpenPoGo/OpenPoGoWeb/issues/164

Ah.  I guess it was only intended for Openpogobot:
https://github.com/OpenPoGo/OpenPoGoWeb/commit/f1d90b570f00d078c5b750175354bd61f15d1833

It's still a great feature, I don't know if its possible to work with PokemonGo-Bot or not but it would be nice.

OS: 
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
6ba5609c6151507b5b832a74e471b6b7b1a182c9

Python Version: (run 'python -V' and paste it here)

**Comment by Tohrment** [comment]
This is a feature I've been waiting for. Would love to pick up the slack where my logic doesn't handle something correctly. Would rather have a gui then try and make the logic work since I am not real familiar with python.

**Comment by BobbyWibowo** [comment]
It was mentioned somewhere that PokemonGo-Bot devs had no desire to implement WebSocket feature. But from what I've seen, they actually seemed to have an interest to do it because as you can see in the config file of the bot, there's an option to enable websocket server (although I'm sure it's still not working for the time being). Oh well, we'll just have to see I guess.

**Comment by oralunal** [comment]
If we can at least evolve from there it will be great option...
