### ISSUE TITLE
Empty screen/terminal (OSx)

### ISSUE THREAD

**Issue by jokoast** [PokemonGoF/PokemonGo-Bot#3029]
Hi everybody, 

I don't know what happens but my terminal turns black, just something like :
print("\n")

You can see this problem here : http://imgur.com/dmrk1f5

It happens a half hour after the launch of the bot and i'm sure it doesn't work during this black screen cause the level of the bot was 7 and in 10 hours, it should be 15 ^^.

Thx again guys,

Jokoast

**Comment by mhdasding** [comment]
@jokoast do you have UpdateTitleStats in your config?

**Comment by jokoast** [comment]
Yes i do have it. A related issue ?

**Comment by mhdasding** [comment]
@jokoast yeah i think so, before a1733b92b9cb4bd5a864ec506e7709d14d56674b the title update would get buffered and could be eventually written to stdout without ending the update titlebar command therefore not showing anything on the terminal because it still thinks it setting the title. Try updating to the latest dev, hopefully it should fix this

**Comment by jokoast** [comment]
I'll remove it first and give it a try to tell you if it's related or not.
Thank you guys :)
