### ISSUE TITLE
[CONFIG] websocket server not starting

### ISSUE THREAD

**Issue by ChrisHaPunkt** [PokemonGoF/PokemonGo-Bot#3079]
I don't get the embedded websocket server to start. Is there more to do as serving:

  "websocket_server": true,
  "websocket_server_url": "0.0.0.0:4343",
  "websocket_start_embedded_server": true,

in the config file?

This feature is not documented anywhere...

OS:  deb8
Git Commit: latest dev
Python Version: 2.7

**Comment by maestroi** [comment]
This is for interfacing with other apps, you can connect for example socket.io with python or node or something, to the interface and you can do everything with logs you want.

In the future there will be ability to change config etc with websocket but thats not implemented.
its not documented because its not fully ready yet.

I hope this helped

**Comment by lawliet89** [comment]
There is no code in `pokecli.py` that merges the websocket configuration from the JSON file into the argument parser as far as I can tell.
