### ISSUE TITLE
Thoughts on '[pokemon_fled] Rattata fled'?

### ISSUE THREAD

**Issue by leadboots5** [PokemonGoF/PokemonGo-Bot#3105]
In the current code when a pokemon breaks out of the ball you get a line like this:
[pokemon_fled] Rattata fled

To me that sounds a lot like they ran away because that is what it means to flee... Do others agree/disagree?
I can submit a change for something else like based on opinions:
[pokemon_breakout] Rattata broke out.

For reference when they disappear you get it:
[pokemon_vanished] Rattata vanished

Thank You.

**Comment by GitPupper** [comment]
I'm happy with it since I don't really stare at the lines of code that run across my screen. Gives me a headache. But I have seen this and yeah it's kinda common knowledge that if it fled that means it escaped something. Cause it obviously has to flee from something. It confused me at first but yeah not worth all that to change what it says.

**Comment by jrjhealey** [comment]
Fled means it actually ran away. If it simply failed ton catch the bottom should (or at least used) to say so. And it would attempt to re-catch. 

If it flees there's nothing you can do.

**Comment by leadboots5** [comment]
This has been merged in by someone else. Closing.
