### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by kickodor** [PokemonGoF/PokemonGo-Bot#3171]
My virsus program just stop the bot right now 01.15 cause it detected a malware virus. have been working fine since the new update but my virus program just kicked in. is this because its a unspessified execute program that my virus program just does not like and it kicks in or is it a malware virus?

Sorry for bad english

**Comment by Thedyolf** [comment]
Most likely this occurred because it's a file not used by many users, which might look as a fake version of a program to a virus scanner. Happens often with some virus scanners if you create your own programs. Not sure which scanner you are using, but most anti-virus programs give you a reason why they think a program is suspicious.

**Comment by kickodor** [comment]
I use Norman

**Comment by mjmadsen** [comment]
I'm sure the API goodness is picked up as malware. It intercepts and alters network data.

**Comment by jrjhealey** [comment]
Just create an exception in your AV software, or disable it while you run the bot.

**Comment by RedViper9** [comment]
As there have been many updates since this issue was posted, I'm assuming this issue has been resolved. If I'm wrong, please reopen.
