### ISSUE TITLE
Prioritize Higher Evolved Pokemon when Evolving

### ISSUE THREAD

**Issue by tr33s** [PokemonGoF/PokemonGo-Bot#3380]
An option to prioritize higher evolved pokemon when evolving would be nice so we don't waste candies on lower evolutions. Obviously not ideal for exp grinding and evolving pidgeys/rats/etc.

**Comment by Gobberwart** [comment]
I second this suggestion. Would be nice to save squirtle candies to evolve a wartortle, rather than having them all used up to evolve squirtles (for example)

I realise I can add individual pokemon to be evolved, but would like to have something like...

1. Do you have candies?
2. If yes, do you have an evolved pokemon?
3. If yes, and it can be evolved, then save candies to evolve it.
4. If no, evolve low-level pokemon

Sorry for crappy pseudocode but I'm sure you get the idea.

**Comment by k4n30** [comment]
Please move your feature request/s to our feature hub - http://feathub.com/PokemonGoF/PokemonGo-Bot

**Comment by k4n30** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/issues/3843#issuecomment-239708680

**Comment by Anakin5** [comment]
Done like that in pokemon optimizer. Should we close or ?
