### ISSUE TITLE
Little help please

### ISSUE THREAD

**Issue by LKKeith** [PokemonGoF/PokemonGo-Bot#3405]
Hi im quite new to this, so i hoped someone could walk me through please. At the moment im stuck with this step : The script will explain what changes it will make and prompt you before the installation begins. Once you’ve installed Homebrew, insert the Homebrew directory at the top of your PATH environment variable. You can do this by adding the following line at the bottom of your ~/.profile file

Where should i add ~/.profile file? Im using mac os btw, thanks guys.

**Comment by iruy** [comment]
I don't remember doing so when installed Homebrew.. Check their website [LINK](http://brew.sh/)

**Comment by LKKeith** [comment]
Thanks for the reply. so i can skip that part of this page? http://docs.python-guide.org/en/latest/starting/install/osx/#install-osx

**Comment by Gobberwart** [comment]
Um, what OS are you running? You can't have a ~/.profile and export PATH. The former is linux/macos, the latter is windows.

**Comment by LKKeith** [comment]
Thanks for the reply mate, OS X El capitan 10.11.5

**Comment by Gobberwart** [comment]
Yeah, sorry about that. Had a migraine yesterday and wasn't concentrating properly. You're correct, these instructions are for OSX and the path statement is valid/relevant.

The PATH environment variable tells the OS where to search for executables, so instead of typing "/usr/local/bin/brew" every time, you can just type "brew" and the system will find the correct location automatically.

In this case, the statement adds /usr/local/bin and /usr/local/sbin to whatever is defined as your current path variable.

I would have expected /usr/local/bin and /usr/local/sbin to already be in your path, but if not, add the export PATH statement to the end of your ~/.profile file.

**Comment by LKKeith** [comment]
Ah i see. Also do you know how i link python to anything if thats needed? 

"brew install python
Warning: python-2.7.12 already installed, it's just not linked"

**Comment by RedViper9** [comment]
Please use this thread for error reporting and feature requests. For help with running the bot, have a look at the #help thread on the slack forum.
