### ISSUE TITLE
React to "You're going too fast!" message

### ISSUE THREAD

**Issue by mico** [PokemonGoF/PokemonGo-Bot#3429]
After last update iOS pokemon asks me to click at "I'm a passenger" when I'm jump to different location too fast. I just switch my iPhone off, then I on it after 200 meter and I got this message.

I think Niantic can count "I'm a passenger" clicks and detect I'm bot if I don't click.
So we need to add reacting to this message if it's sending something to server when I click "I'm a passenger".

https://twitter.com/PokeWire/status/762809914586693632/photo/1

**Comment by licklake** [comment]
Well, you get this message only if you travel with more then 14km/h. I don't think anyone would set this option above this value because of egg hatching...

**Comment by mico** [comment]
I use teleport when I see rare pokemons. Sometimes I teleport from my home location to far away places.

**Comment by DanielVolz** [comment]
@mico than the not clicked dialog is the least of your problems, in terms of possibly being banned.

**Comment by YvesHenri** [comment]
@licklake your argument is.... well, people do use snipping (teleporting) and that counts as 'moving too fast', since you switch locations very quickly (send information of your current position and the desired one to their servers). also, people do use speeds higher than 14km/h and yes, it does hatch eggs.
