### ISSUE TITLE
How to exit with a report. Also loading with a summary too.

### ISSUE THREAD

**Issue by spoxus** [PokemonGoF/PokemonGo-Bot#3560]
1) Sometimes, I quit with ^C in Windows. Is there any other way to quit?
I also want a report sometime it brings, with a summary report like how many pokemons I got, which is the strongest in cp and iv, etc.

2) Also, when starting the bot, I want a option to take a look at which are my five strongest pokemons too. If there is a option in config file, that would be great.

**Comment by leadboots5** [comment]
1. That is the proper way to quit. It provides that in the report thats already provided when you exit.

2. That is not in the bot and seems oddly specific. Probably better off hoping for someone to put in some sort of export or a plugin that can export your pokemon so you can look at them.

**Comment by k4n30** [comment]
@spoxus 
1. Have u tried using the title stats config - https://github.com/PokemonGoF/PokemonGo-Bot/blob/dev/pokemongo_bot/cell_workers/update_title_stats.py Although it doesnt exit, it gives u a live update of some of the detail you're after.  

2. As for the 5 strongest pokemon, have you tried using the web interface to the bot? You can look at the detail you're after plus much more due to the dynamic nature of the web interface - https://github.com/OpenPoGo/OpenPoGoWeb/blob/master/README.md Because it's already a submodule of the bot, there's not much else you need to do to get it running (follow the steps on the link)
