### ISSUE TITLE
Encounter few Pokemons

### ISSUE THREAD

**Issue by 0z4ck** [PokemonGoF/PokemonGo-Bot#3562]
This morning I woke up to find my bot being almost unable to encounter pokemons.

And I put my bot Location where there are many pokemons , and ran , but the bot didn't detect nearby pokemons.

maybe a kind of new softban ?

**Comment by RedViper9** [comment]
Were you getting some pokemon or none at all? There have been users reporting bans on IP ranges and that may be what you are experiencing. Try running the bot through a VPN to test.

This type of issue is best discussed on the slack board since it doesn't have to do with the operation of the bot itself. 
Check out our chat room! https://pokemongo-bot.herokuapp.com/
