### ISSUE TITLE
Recreated issue: 'status_code': 2, 'unknown6': [{ 'response_type': 6, 'unknown2': { 'unknown1': 1L}}]}

### ISSUE THREAD

**Issue by veil98** [PokemonGoF/PokemonGo-Bot#3684]
I opened up an issue for this about a week ago.  This issue was never resolved, however it the issue was closed.  So, I am creating a new issue in hopes to solve it. 
I am on Mac OS. I downloaded an encrypt.so file online which solved the `OSError: dlopen(encrypt.so, 6): image not found` problem.  Next, I ran `pip2 install -r requirements.txt --upgrade`, and everything was up to date.  I then ran `python pokecli.py -a ptc -u blah -p blah -l “blah”` and got the error message:

'status_code': 2,
'unknown6': [{ 'response_type': 6, 'unknown2': { 'unknown1': 1L}}]}

Any idea what needs to be done now?

**Comment by k4n30** [comment]
You need to use the issue template and fill out the relevant fields so that we can help you.

Based on the error you have posted, and limited other information my suggestion is that you are running severely old code. Please update to the latest version and try to run that. This error was from the pre new api code (4-5 days ago)

**Comment by veil98** [comment]
@k4n30 is this not the most updated version? https://github.com/keyphact/pgoapi

**Comment by doctordo0m** [comment]
did you run `git pull`?

**Comment by k4n30** [comment]
@veil98 I suggest you follow the instructions in the link in my earlier comment as the pgoapi version is irrelevant in this discussion (the update script will pull the right version)
