### ISSUE TITLE
spinning pokestop works but pokemon vanished. is it a new kind of ban?

### ISSUE THREAD

**Issue by fajar125** [PokemonGoF/PokemonGo-Bot#3691]
### Expected Behavior
bot can catch pokemon

### Actual Behavior
2016-08-12 12:43:36,414 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Pi
dgey appeared! [CP 324] [Potential 0.44] [A/D/S 5/13/2]
2016-08-12 12:43:39,380 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Greatb
all, with chance 45.74 (29 left)
2016-08-12 12:43:40,667 [PokemonCatchWorker] [INFO] [pokemon_vanished] Pidgey va
nished!
2016-08-12 12:43:47,009 [CatchLuredPokemon] [INFO] [lured_pokemon_found] Lured p
okemon at fort The Hook (730ed5e1081740a5a7cdd5e85a0844cf.16)
2016-08-12 12:43:47,461 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Ps
yduck appeared! [CP 295] [Potential 0.36] [A/D/S 0/6/10]
2016-08-12 12:43:51,193 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeba
ll, with chance 45.14 (95 left)
2016-08-12 12:43:51,582 [PokemonCatchWorker] [INFO] [pokemon_vanished] Psyduck v
anished!
2016-08-12 12:43:56,973 [  SpinFort] [INFO] [spun_pokestop] Spun pokestop The Ho
ok. Experience awarded: 50. Items awarded: {u'Pokeball': 1, u'Greatball': 2}
2016-08-12 12:43:59,592 [MoveToFort] [INFO] [moving_to_lured_fort] Moving toward
s pokestop Cable Car - 0.07km (attraction of lure 0.07km)
2016-08-12 12:44:03,006 [PokemonCatchWorker] [INFO] [pokemon_appeared] A wild Ma
gikarp appeared! [CP 170] [Potential 0.64] [A/D/S 11/3/15]
2016-08-12 12:44:06,900 [PokemonCatchWorker] [INFO] [threw_pokeball] Used Pokeba
ll, with chance 41.11 (95 left)
2016-08-12 12:44:07,305 [PokemonCatchWorker] [INFO] [pokemon_vanished] Magikarp

is this a ban?

**Comment by celus** [comment]
same for me

**Comment by philly223** [comment]
Having exact same issue. Bot was working perfectly fine for 12 hours, stopped for a few minutes and then continued again. Pokemon only vanishes

**Comment by k4n30** [comment]
Anyone else experiencing this?

**Comment by DXjohn** [comment]
I cant spinning pokestops, but i can catching pokemons...

**Comment by k4n30** [comment]
Interesting now a lot of people are reporting server offline issues, but only on bot accounts #3682

**Comment by DXjohn** [comment]
I do not understand much, but I think it will be something on PoGo servers. When I tried a different bot, it was the same problem.

**Comment by fldc** [comment]
It's the same here since some hours ago.

**Comment by focamonca** [comment]
I confirm, it's a new soft-ban!

**Comment by AcorpBG** [comment]
One of my accounts got banned don't think it is soft ban perm more likely Can't login from app too only 1 account so far.

**Comment by fldc** [comment]
I can login just fine from the app, spin pokestops and fight in gyms just fine, just don't catch any Pokémon.

**Comment by KingTheRipper** [comment]
Confirmed is NOT a new soft-ban! there are a problem with the login server in the world, here a same issue we have in a italian news (use chrome to translate) http://servizioallerta.it/problemi/pokemon-go/novita/66422-problemi-a-pokemon-go

Same for me, from the app "Is impossible take your data from the server"
We have only to wait ;)

**Comment by heisch** [comment]
@KingTheRipper: Can't confirm your findings

I have the described Issues with one account, but not with the other, so it's definitely a new kind of soft(?)-ban. Also a friend of mine who is sitting next to me, has no problems whatsoever.

**Comment by p1n9** [comment]
Same for me =(

**Comment by LostDGod** [comment]
I have the all pokemon vanishing issue (on a google account) as well. 
>Tried the game with bluestacks, still the same problem. 
>Tried account2 (ptc) (this one has been used by the bot before but not for the past 24h), i was getting a weird freeze error at first when trying to enter battle but once i could enter i had no problems catching the poke. It works.
>Tried the bot with account2 and it works.
>Jumped very high distance with account2 to softban it on porpose and waited for the bot to un-softban and try to catch poke. It works.
>Tried account3 (google) (just like account2, this one has been used by the bot b4 but not recently), it works.
This should confirm its a problem in account(1) and **NOT** the servers as some people have been mentioning for some reason.
I noticed I was sometimes getting 600+ and even 700+ XP from catching on account3. My catch throw parameters were a bit overkill:


> "catch_throw_parameters": {
>       "excellent_rate": 0.4,
>       "great_rate": 0.6,
>       "nice_rate": 0.4,
>       "normal_rate": 0.1,
>       "spin_success_rate" : 1

My guess is the server can now detect a bot when its throwing 'perfect' throws way too often **OR** it already did and this is something the new 'config' brought up.

**Comment by Waliers** [comment]
During the initial launch issues some people could login others could not. Some people could spin, others could not. Some people could catch, other got the spinning pokeball of death. Moral of this story? Just because one of your accounts works doesn't mean the other is banned... Don't yell SOFTBAN everytime something stranges happens... Most of the time during launches I was watching my GF play (on a Google account) and I get the "hummbled server" (on a Google account) or vice versa. It was not a softban... It was server issue. Sometimes data flows through sometimes it doesn't. 

Try to understand Niantic has multiple servers (NOT JUST ONE!) which overload during patches and new regions or new features).

Account A is on Server A. This server is overloaded since it's the closest to <Insert new region here>and holds a lot of accounts.
Account B is on Server B. This is a new server with only a few accounts so little login request and data during the new region launch. It fills up during the launch.

Account A can't do anything. Server is overloaded so even if you managed to login your data isn't handled hence you won't see pokemon and/or can't spin and Error out a Gym.

Account B is working since the server isn't under a high load. So this account can catch pokemon and Spin. (However in the past we seen this crash to when the load increases but thats another story). 

Now imagine this with a lot more servers, country's and regions and issues here and there with different parts of hardware, software and connections...

Offcourse this is not how it works but hopefully this makes you think a bit more about how an IT infrastructuur works and don't blindy assume your bant or say there are no server issues since "account blabla is working so there is nothing with the servers must be the bot or ban".

Also take a look at [http://downdetector.com/status/pokemon-go](http://downdetector.com/status/pokemon-go) when in doubt.
Your accounts (one or more) might be working but a lot of other people are also reporting server issues arround the globe... Maybe... Just maybe it IS a server thingy.......

**Comment by LostDGod** [comment]
@Waliers you wrote all of that just to say that accounts may be linked to different servers regardless of login position. xD
I admit though, I didn't know that. I'm now putting my hopes on what you said.

**Comment by Waliers** [comment]
Well... It's a bit more complicated but you can see it like that yeah.

**Comment by cnoekkii** [comment]
Have exactly the same issue ..
I can collect items from pokestop, but can't catch any pokemon

**Comment by k4n30** [comment]
#3700

**Comment by omkar2023** [comment]
I'm Having The Same Issue Since Last 4 Hours... I can Get Items from POKESTOPS but Can't Catch POKEMONS and Also Not being able to BATTLE in GYM..
