### ISSUE TITLE
new update and still ecounted pokemon

### ISSUE THREAD

**Issue by pascaltiel** [PokemonGoF/PokemonGo-Bot#3712]
Hello can someone help me whit this issue pls ?
i have the newest update but still he encounted all the pokemons 
how can i fix this allready thanx for the help

- 
![print](https://cloud.githubusercontent.com/assets/20987673/17618308/306c30a2-607f-11e6-9f5e-200fc2c4dd64.png)

**Comment by nivong** [comment]
polaes use the issue template or we cant help you.

**Comment by pascaltiel** [comment]
what is a template ? sorry for this question

**Comment by Waliers** [comment]
The template u see when making a new issue...  Fill this in. Don't delete everything but read it and fill in the blanks:

It looked like this (before you CTRL+A, DEL it :P)

_## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior


### Actual Behavior


### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Steps to Reproduce


### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)_
