### ISSUE TITLE
encrypt.so is not found

### ISSUE THREAD

**Issue by Jarhead6** [PokemonGoF/PokemonGo-Bot#3937]
hey how can i fix that?
2016-08-14 18:18:20,881 [PokemonGoBot] [ERROR] encrypt.so is not found! Please place it in the bots root directory or set encrypt_location in config.
2016-08-14 18:18:20,881 [PokemonGoBot] [INFO] Platform: darwin Encrypt.so directory: /Users/dennis/Desktop/Pokegobot/PokemonGo-Bot

**Comment by DiegoRBaquero** [comment]
If you did a manual installation you missed the encrypt.so part: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/manual_installation.md

**Comment by Cetino** [comment]
take a look at: https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/manual_installation.md#windows (bottom of page)
or simply place this dll in your root folder:
[encrypt_64.zip](https://github.com/PokemonGoF/PokemonGo-Bot/files/417122/encrypt_64.zip)

**Comment by Jarhead6** [comment]
how can i place it in my root folder?

**Comment by Jarhead6** [comment]
now i get 
ERROR] [u'OSError: dlopen(/Users/dennis/Desktop/Pokegobot/PokemonGo-Bot/encrypt.so, 6): no suitable image found.  Did find:\n\t/Users/dennis/Desktop/Pokegobot/PokemonGo-Bot/encrypt.so: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00', u'  File "pokecli.py", line 578, in <module>', u'  File "pokecli.py", line 145, in main', u'  File "pokecli.py", line 180, in report_summary', u'  File "pokemongo_bot/metrics.py", line 84, in capture_stats', u'  File "pokemongo_bot/api_wrapper.py", line 106, in call', u'  File "pokemongo_bot/api_wrapper.py", line 63, in _call', u'  File "pgoapi/pgoapi.py", line 210, in call', u'  File "pgoapi/rpc_api.py", line 85, in activate_signature', u'  File "ctypes/__init__.py", line 443, in LoadLibrary', u'  File "ctypes/__init__.py", line 365, in __init__']

**Comment by jrjhealey** [comment]
If you're on Darwin you may well have to compile the encrypt.so file yourself rather than simply downloading an existing one (someone may be able to correct me if Darwin is simply capable of using another *NIX .so file).

Run the following command from inside your PokemonGo-Bot folder:
`wget http://pgoapi.com/pgoencrypt.tar.gz && tar -xf pgoencrypt.tar.gz && cd pgoencrypt/src/ && make && mv libencrypt.so ../../encrypt.so`

If that fails I would suggest you delete that folder and start your installation over from scratch and ensure you follow each instruction in the documentation _to the letter_
