### ISSUE TITLE
Spam: CATCH_POKEMON "status": 3

### ISSUE THREAD

**Issue by crack00r** [PokemonGoF/PokemonGo-Bot#4]
Sometimes it spams this for over 5minutes, then i have to break the script, and start again

2016-07-21 08:58:59,619 [    pgoapi] [ INFO] Create new request...
2016-07-21 08:58:59,621 [    pgoapi] [ INFO] Adding 'CATCH_POKEMON' to RPC request including arguments
2016-07-21 08:58:59,622 [    pgoapi] [ INFO] Execution of RPC
2016-07-21 08:58:59,943 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary:
{
  "unknown2": 8145806132888207460,
  "direction": 1,
  "auth_ticket": {
    "expire_timestamp_ms": 1469086143667,
    "start": "5CpLERrRb5ZQphR+vw0n61XTQVlM9W4moeUCvFyeXYm2GzFQ5ZIN0Hkb2+MkOMjxo1ZpP4GIO/CM\nGTLDv46bbQ==\n",
    "end": "2Cx/pEQjUoR2E5zicpeWLw==\n"
  },
  "responses": {
    "CATCH_POKEMON": {
      "status": 3
    }
  }
}

**Comment by system123** [comment]
It is most likely because you have been soft banned so all the encountered Pokemon run away. Try not change location too drastically as the server monitors for unfeasible location changes. It seems to calculate a delta between your last login and your current one, and determine the speed traveled to get there.

**Comment by crack00r** [comment]
ok, just travel arround 500m, to another spot, but thx :D

**Comment by PokemonGoF** [comment]
no... just fixed this bug.

**Comment by PokemonGoF** [comment]
https://github.com/PokemonGoF/PokemonGo-Bot/commit/8b5467e0b04bf68e7b505f897325422995828e36
