### ISSUE TITLE
Nickname config, favorite still get renamed.

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#4009]
### Expected Behavior
when you set "dont_nickname_favorite": true
favorite should not be nicknamed.
I think i posted it some time ago, but could not find it.
### Actual Behavior
They still get renamed.
### Your config.json (remove your credentials and any other private info)
```
{
	"type": "NicknamePokemon",
	"config": {
		"nickname_template": "{ivcp_pct2}%{iv_ads}"
	},
	"enabled": true,
	"dont_nickname_favorite": true,
	"good_attack_threshold": 0.7
}
```

**Comment by BriceSD** [comment]
@avexus Need more infos. 
## Stop! Before you create this issue (you can delete this section when opening the issue):
1. Have you validated that your config.json is valid JSON? Use http://jsonlint.com/ to check.
2. Have you searched to see if there are other issues for the same issue? If so, comment on that issue instead.
3. Are you running `master`? We work on the `dev` branch and then add that functionality to `master`. Your issue may be fixed on `dev` and there is no need for this issue, just wait and it will eventually be merged to `master`.

### Expected Behavior


### Actual Behavior


### Your config.json (remove your credentials and any other private info)
```
your config here
```

### Steps to Reproduce


### Other Information
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by avexus** [comment]
@BriceSD   It's like this. I have several pokemons marked as favorite. I gave them special names. But when I run the script, they all gets renamed after the "nickname_template".
If I set
"dont_nickname_favorite": true,
They should not be renamed.

**Comment by BriceSD** [comment]
OS:
Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)
Python Version: (run 'python -V' and paste it here)

**Comment by avexus** [comment]
It seems fixed now.
