### ISSUE TITLE
Request: Ignore pokemon when have no ball inside inventory (if not, hard ban)

### ISSUE THREAD

**Issue by ipenpen** [PokemonGoF/PokemonGo-Bot#4062]
**Problem:**
  When number of poke ball inside inventory become 0, and catchable pokemon appear, my character always try to catch the same pokemon. This action will repeat until pokemon disappear. And next day my account get hard ban ....

**Request feature:**
  Character will ignore any pokemon when number of ball inside inventory is 0.

**How to fix:**
  Add validate number of poke ball inside inventory to "pokemon_catch_worker.py" file.

Hope it help!

p/s: i donnot know how to add feature request label, some one help me plz.

**Comment by avexus** [comment]
Well, this kind of behavior is suspicious.

**Comment by iruy** [comment]
Is it be possible to automatically remove from task configuration: `CatchLuredPokemon` and `CatchVisiblePokemon`? And force `FollowSpiral` together with `MoveToFort` and `SpinFort` if not present. 
This would help a lot with `FollowPath` task which doesn't work very well together with `MoveToFort`

**Comment by youberser** [comment]
It happened to me few times... I solved it by having a crontab and 2 config files.
Each 30 min the bot stop catching pokemons and just farm pokestops for 5 mins

**Comment by antistes** [comment]
This problems exists since a while. It maybe only related to FollowPath mode. There was never really a fix beside the introduction of using ultraballs if no other ball is available. The bot stops moving when a lured or wild pokemon appears and there is no ball available. Without moving it will try to catch it forever and dont spin a fort to get new balls.
