### ISSUE TITLE
[MoveToMapPokemon] Efficiency improvements in moving to Pokemon (last steps)

### ISSUE THREAD

**Issue by k4n30** [PokemonGoF/PokemonGo-Bot#4157]
### Short Description
[MoveToMapPokemon] stop going "the last bit (30-40m)" to a Pokemon's location after it has been seen and caught as the task is set to move to it's location, but is generally seen just before hitting that location.

### Possible solution
Update the logic in the MoveToMapPokemon to complete earlier? 
Detect for the Pokemon it's after?

### How it would help others
Efficiency dividends
Prevents issues like #4143

**Comment by RedViper9** [comment]
I'd love to see this, but it looks like a problematic thing to develop.
My bot often finds random pokemon while on the way to MapPokemon. These randoms presumably don't show up on my Map instance so MoveToMapPokemon can't target them.

Can we differentiate between the Pidgey encountered randomly and Pidgey spawn targeted by MapPokemon? What happens if we encounter a random Pidgey while moving to MapPokemon-Pidgey?

Would it be sufficient to continue to the next MapPokemon if you catch ANY pokemon that is identical to your current target?

**Comment by k4n30** [comment]
I'd say this a feature request for an enhancement to move to map. This task seems to cause most people grief and seeing as bans seemed to be being blamed on "teleporting" tasks this should either be disabled or refactored to be more human like.

If the fix option is chosen then this should be considered as part of the rewrite
