### ISSUE TITLE
[MoveToMapPokemon] Sometimes pokemon is only encountered but not caught

### ISSUE THREAD

**Issue by jane0815** [PokemonGoF/PokemonGo-Bot#4223]
Unfortunately my issue from yesterday was already closed so i could not add a log after the same error occured again!

Here is the old issue: https://github.com/PokemonGoF/PokemonGo-Bot/issues/4167

**Expected Behavior**

All bots move to same pokemon and catch it.

**Actual Behavior**

Sometimes some bots move to the pokemon but do not catch it. The log says only encountered pokemon and then it moves on to the next.

**Your FULL config.json (remove your username, password, gmapkey and any other private info)**

All bots run the same config, all see the VIP pokemon and move there but only 4 out of 5 catch the pokemon.

2016-08-18 20:xxxxxxx [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Exeggutor, 0.13km, left (5 minutes, 49 seconds)
2016-08-18 20:xxxxxxx [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Exeggutor, 0.09km, left (5 minutes, 47 seconds)
2016-08-18 20:xxxxxxx [MoveToMapPokemon] [INFO] [move_to_map_pokemon_encounter] Encountered Pokemon: Exeggutor
2016-08-18 20:xxxxxxx [MoveToFort] [INFO] [arrived_at_fort] Arrived at fort.
2016-08-18 20:xxxxxxx [FollowSpiral] [INFO] [position_update] Walking from (X ,Y, 0) to (X ,Y,, 0) (885.219706971 m)
2016-08-18 20:xxxxxxx [  SpinFort] [INFO] [spun_pokestop] Spun pokestop xxxx. Experience awarded: 50. Items awarded: {u'Razz Berry': 1, u'Pokeball': 2}
2016-08-18 20:xxxxxxx [MoveToMapPokemon] [INFO] [move_to_map_pokemon_move_towards] Moving towards Aerodactyl, 1.32km, left (1 minute, 54 seconds)

_I removed times, gps coordinates and stop name._

@k4n30 I am not to lazy to fill out the form! If you read what i wrote you might have realized that it is not a config problem because all accounts use the same file. All run on the same OS, same java same everything!!!

**Comment by net8q** [comment]
Your config is relevant, you're probably using too aggressive settings and getting somehow softbanned on some accounts, you may read this issue https://github.com/PokemonGoF/PokemonGo-Bot/issues/3989 for more information

**Comment by RedViper9** [comment]
Related:?
MoveToMapPokemon will continue to the center of the spawn area after catching the mapped pokemon.

Pokemon spawn in an area around the server reported location, but the bot continues to the exact GPS coordinates of the spawn point. It would be preferable to move on to the next pokemon instead.

**Comment by jane0815** [comment]
Well I set the bot to quite high speed (25-50) but they only move within a small area. Never had any softbans yet with those settings. And still 4 out of 5 accounts caught it with the same settings. Started at the same time, from the same position. Everything is the same.

Also when i restart the bot that missed the VIP catch it will run to the same pokemon again and catch it so softban is not possible. When trying to catch a pokemon in softban it will run away after first ball. This does not happen. 

The pokemon is only encountered but then the bot moves on to the next too fast.

**Comment by RedViper9** [comment]
@jane0815 When the console says "Encountered (POKEMON)", this does not mean that it encountered anything. This is the default message printed by MoveToMapPokemon when you reach the coordinates specified. MoveToMapPokemon does not know if you caught anything or not, it only moves. once you get to the spawn point, that point is cached and bot moves on to next pokemon in the list.

**Comment by RedViper9** [comment]
```
    def _encountered(self, pokemon):
        """Emit event when trainer encounters a Pokemon.

        Args:
            pokemon: Pokemon encountered.
        """
        self.emit_event(
            'move_to_map_pokemon_encounter',
            formatted='Encountered Pokemon: {poke_name}',
            data=self._pokemon_event_data(pokemon)
        )
```

```
        if not step_walker.step():
            return WorkerResult.RUNNING
        self._encountered(pokemon)
        self.add_caught(pokemon)
        return WorkerResult.SUCCESS
```

**Comment by k4n30** [comment]
@RedViper9 another candidate for fixing the movetomap task

@jane0815 Yes in your eyes there is nothing wrong with your config, but we need to be able to read and analyse it to determine if it is causing the issue or not. It doesn't matter if you are using it across other bots or not, it may only be an issue in certain circumstances. We have a template for a reason and that is to HELP US help you, if you don't want to use it because you think you know better, than don't be surprised if you don't get any help.

Anyway as this is not a bug as such, is this really a feature request now what we know what the cause is?

**Comment by kenkclam** [comment]
I had the same problem before. I guess either the coordinate is not exact (I don't have the same problem when I am sniping) or it takes some time for the pokemon to pop up even if you are at the exact co-ordinate already.
So, I set the bot slow enough (1-4) so that it walk around the coordinate for around 10 seconds, and I also removed a lot of pokemon from my list so that the bot does not need to chase after another one after the first encounter. Now I rarely see the bot missing anything. 

Btw, is there a way to set a time delay between MoveToMapPokemon jobs? 
I want the bot to have 15 seconds walking around after encountering a pokemon, rather than chasing another one almost immediately.
