### ISSUE TITLE
Web inventory doesn't get updated

### ISSUE THREAD

**Issue by NovaDev94** [PokemonGoF/PokemonGo-Bot#4337]
### Expected Behavior

`web/inventory-<username>.json` file get updated after Pokemon catched, Fort spinned,...

### Actual Behavior

`web/inventory-<username>.json` is only written on bot start, in the `Inventory` constructor (calling `self.refresh()`). The file doesn't get updated after that.  

### Other Information

I got this unexpected behavior after #4238 is merged. Maybe some calls is missing to update the web inventory, or that's the new expected behavior?

**Comment by Anakin5** [comment]
That is expected but that would be nice to do some thing about it.
The inventory.json was supposed to hold the full response from the api, but since we do not call the api anymore, it is not updated.

Which lead to other questions:
- Can we change the format of the inventory.json to store our internal inventory instead of the api one ?
- Would it require changes in the web module ?
- What is the status of the web interface anyway ? I do not yet understand why there is some websocket, event logger, database etc... since there is no interface to communicate with them.

**Comment by k4n30** [comment]
@douglascamata & @brantje ^

**Comment by NovaDev94** [comment]
I think the only way to monitor the "catched" Pokemon now is to use the web interface since the desktop version is pretty much broken for now.  

Could we just provide a config for "refreshing the inventory & dump to file" with interval? That config will be disabled by default for sure.

**Comment by Gobberwart** [comment]
The web interface is broken as well. api inventory refresh is now only called once during recycle, and then only if min_empty_space is exceeded. In my case, that's about once per 90 minutes.

Should be refreshing inventory once per bot tick? Or at least every few minutes.

**Comment by NovaDev94** [comment]
@Gobberwart The web interface still works fine for me (with the purpose of managing my Pokemon list and also the items).  

It's sad that I can't do it anymore with the new cached inventory :(.

**Comment by BriceSD** [comment]
We’re moving away from writing in files. With our new map we won’t need it anymore. That being said, it’s not ready yet. I guess there is quite a lot of people who want this. Refreshing the inventory at every tick could be a temporary solution.

**Comment by Gobberwart** [comment]
I've included this in my PR #4513 as part of the item recycler update. Once (if) approved/included, the web inventory should update every tick, without needing api call.
