### ISSUE TITLE
Telegram bot integration

### ISSUE THREAD

**Issue by weirdapps** [PokemonGoF/PokemonGo-Bot#4353]
### Short Description
Telegram bot integration for remote progress updates

### Possible solution
Integrate a telegram bot feeding mechanism so that users can see their bots progress while away

### How it would help others
Users will be able to remotely check progress and see if bot is active and request basic stat updates: active time, XP gained, stardust gained, pokemons caught, XP per hour, stardust per hour, pokemons per hour, item list, pokemon list ordered by highest cp, iv, time, etc.

*by the way, many thanks for the effort you are putting in. Great experience so far.

**Comment by askovpen** [comment]
[PokemonGo-Bot-Telegram](https://github.com/askovpen/PokemonGo-Bot-Telegram)

**Comment by weirdapps** [comment]
that's great! Any chance of instructions? Guessing put the .py file where you want, add the parameters in the config file. Then what?

**Comment by askovpen** [comment]
i added instructions

**Comment by weirdapps** [comment]
much appreciated, thanks!

**Comment by LitRidl** [comment]
@askovpen That's great solution if we want to keep things separate, but it uses files and etc. For example, if we have distributed Docker configuration -- it would not be convenient to manage those things.
I think that in terms of original request maybe it would be better to implement Telegram logging handler. By the way, it is very easy because it is almost done already: https://github.com/python-telegram-bot/python-telegram-bot
This way we may selectively send some logging messages to Telegram or buffer them and send in bulk.

**Comment by askovpen** [comment]
plugin for bot: https://github.com/askovpen/telegram-pgo-plugin

**Comment by mjmadsen** [comment]
Merged
