### ISSUE TITLE
Play from a single location

### ISSUE THREAD

**Issue by krishven** [PokemonGoF/PokemonGo-Bot#4627]
### Short Description

Avoid bot detection by playing from single location.

### Possible solution
Just set single location and set play from same location to true.

### How it would help others
Avoid bot detection

I don't know if it is already possible to do this. If so, Please let me know how to before closing the issue.

**Comment by acurioustale** [comment]
Use FollowPath with a local GPX route. You can easily create routes that follow sidewalks or bike paths with [GPSies](http://www.gpsies.com/). Just include a handful of stops that an actual player could easily reach.

**Comment by innrwrld** [comment]
You can also just set said location & disable the variable to walk to forts, which I think in my next testing I may do.  Allow said bot to camp a location, sit for an hour, go offline until later in the day rather than trying to path to a lot of local forts.  

I also think setting up followpath is a good idea of which I've not yet tested, but aligns more with actual human interaction in following walkways & such as @acurioustale mentioned above.  There very well may be some algo server side looks at "Trainers" (bots) just walking through people's yard & such to get to a PokeStop when realistically most people would not do that & instead follow pathways.

**Comment by kashyapjha** [comment]
@innrwrld I've been walking through yards, water bodies, buildings and never had a problem. Using GPSJoystick currently though, not a bot.

**Comment by mjmadsen** [comment]
#4536
