### ISSUE TITLE
Captcha screen - App update 1.5.0

### ISSUE THREAD

**Issue by javierpalopez** [PokemonGoF/PokemonGo-Bot#4671]
http://pokemongohub.net/captcha-game-pokemon-go-bots-trackers/

As soon as the game detects abnormal player behaviour, the player is prompted with a simple captcha screen.

**Comment by Gzerox** [comment]
This is not confirmed yet, is it ?

If is real, this should be a pain in the ass :\

**Comment by maxprzemo** [comment]
It can only be used to register player?

**Comment by sohje** [comment]
Any screenshots with captchas from app?

**Comment by duttonw** [comment]
the diff from the andriod app shows recaptcha and web browser to support it included. :'(

**Comment by drricksanchez321** [comment]
So it sounds like any server response may come with a captcha challenge request.. all further actions prohibited until a valid response is sent.. If the challenge is only triggered from 'abnormal' behavior, the goal of the bot going forward should be preventing the captcha challenge request rather than cracking the captcha (but that's pretty obvious?). For that.. we'd need to be able to solve the captchas when they arise through the bot.. spawning some browser window with the captcha script, collecting the hash and attaching to the response. Recaptcha uses the hash and the remote IP to validate -- since we'd solve it on the same machine as the bot, the IP would match.

**Comment by supergithubo** [comment]
On the good side, we'll now determine what specific behavior will trigger suspicious activity :)

**Comment by mjmadsen** [comment]
Better get to reading:
https://www.blackhat.com/docs/asia-16/materials/asia-16-Sivakorn-Im-Not-a-Human-Breaking-the-Google-reCAPTCHA-wp.pdf

**Comment by mjmadsen** [comment]
@k4n30 We'll be needing an issue for this as soon as they activate that portion of code.

**Comment by k4n30** [comment]
Agreed, but right now it's not an issue with the bot, and will only get lost if it remains open until it becomes an issue. Could be a feature request though :p

**Comment by mjmadsen** [comment]
I'm fine with that. :+1:
