### ISSUE TITLE
Evolve only certain pokemons for PokemonOptimizer

### ISSUE THREAD

**Issue by hobbes3** [PokemonGoF/PokemonGo-Bot#4693]
### Short Description

Evolve only a list of pokemons for `PokemonOptimizer`

### Possible solution

Have a new setting in `config.json` like
 
    "evolve_list": "Caterpie,Ekans,Goldeen,Krabby,Pidgey,Rattata"

or
    
    "evolve_list": "all"

### How it would help others

The `PokemonOptimizer` is great but I wouldn't want the bot to evolve a Dratini or Growlithe. I would rather do that manually so I can see the moves later.

**Comment by 4IbWNsis3S** [comment]
"EvolvePokemon" in "tasks" already does exactly what you describe..

**Comment by Anakin5** [comment]
@hobbes3
The PokemonOptimizer tries, as much as possible, to not require static names and values from you since they tend to change over time.

However you achieve what you describe by setting evolve=false in all your "keep" condition, and then have another with names=[your list] and evolve=true.

About you comment on moves, what do you mean exactly ? what decision are you taking manually that the bot cannot take ?

**Comment by lntn** [comment]
can we use PokemonOptimizer in conjunction with EvolvePokemon?

**Comment by mjmadsen** [comment]
I wish all of these were merged. I'll take a gander (soonish).

**Comment by hobbes3** [comment]
@4IbWNsis3S Ya, but `PokemonOptimizer` can automatically evolve after there is enough pokemons to evolve for 1 lucky egg. For `EvolvePokemon` you'll have to do it manually since from my experience, it only pops a lucky egg in the beginning (so if you are still evolving after 30 minutes then it won't pop another egg).

@Anakin5 Sometimes I don't want to evolve Dratinis when I have over 25 candies since I want to save those candies for powering up Dragonites.

**Comment by Anakin5** [comment]
@hobbes3
Even if those Dragonies are inferior to your Dratini ?

**Comment by Baconnaise** [comment]
The pokemon with two evolves can be a problem if you have Evolve All set. Generally that requires 150 candy depending on the type to reach final evolve. Bellsprout, Oddish, Dratini, and others usually require a bank of candy to hit final evolve. Totally get what Hobbes is saying here. I would think it would be easier to get this sort of functionality by ignoring specific pokemon similar how to only evolve listed pokemon (weedle, pidgey, and etc). You can sort of do this now but you would have to list all the pokemon you want to evolve (most of them) to get it to ignore dratini for example in your case. That or turn it off entirely.

**Comment by Anakin5** [comment]
I still do not get why you would use your candies to power up a Dragonite if you have a Dratini which is better. Wouldn't it be better to evolve and power up that Dratini ?

**Comment by hobbes3** [comment]
@Anakin5 First I only keep Dratinis that are over 0.9 IV. I would rather have 100 candies in the bank to power up my 3 Dragonites to max CP, than to have 5 more Dragonairs (evolving a Dratini times 5 = 100 candies) with no leftover candies for my 3 Dragonites.

Basically I want to evolve for XP, but I only want to evolve Pokemons that I don't care about their candies, ie Pidgeys, Rattatas, Caterpies, etc.

**Comment by Anakin5** [comment]
I understand, but are those 3 Dratini better iv than the Dragonite ? Do they have equal iv ?
If you have a Dratini 1.0 and 3 Dragonite 0.93, what do you want to do with the candies ?

**Comment by Baconnaise** [comment]
If his Dragonite has the best moveset despite being .93 IV then he likely wants to power that up since it's more useful now and is a sure thing. Dratini with 1.0 IV isn't a sure thing and if it's low CP to start with (generally they are in my experience) he would need a massive amount of dust and candy to evolve to Dragonite to max. I thought it was pretty clear.

**Comment by Anakin5** [comment]
@Baconnaise 
I wish it is that simple. If it was that, then there is easy way to not evolve the Dratini.
If the Dragonite is kept as a result of:
```
{
    "top": 1,
    "sort": ["cp"]
}
```

or

```
{
    "top": 1,
    "sort": ["dps"]
}
```

and Dratini because of:
```
{
    "top": 1,
    "sort": ["iv"]
}
```

then, the only thing to change is:

```
{
    "top": 1,
    "evolve": false,
    "sort": ["iv"]
}
```

So I am going to assume that the reason why this Dratini should not be evolved is something else.

**Comment by hobbes3** [comment]
Honestly, I just want a top level blacklist of Pokemon that the `PokemonOptimizer` will NOT try to evolve.
