### ISSUE TITLE
[Discussion] Modules

### ISSUE THREAD

**Issue by mzupan** [PokemonGoF/PokemonGo-Bot#476]
I have a skeleton for modules but really don't want to work on this repo since dev just changes way too quickly. If things are changed I'll push the changes.. The idea is like

```
modules/
   pokemon/
      nameHere.py
      nameHere.yml
      otherNamehere.py
      otherNamehere.yml
```

The idea is there is a skeleton of what to do when you see this type of pokemon. Is it a very high CP? if so catch it. So I need to evolve or power up then do it. I have too many or too many cookies? Then skip this one. 

Also I reworked a lot of the map and it runs flask and its almost like a control plane for the bot 
Also it seems the bot has no logic when walking and I'm trying to fix that by having it do some research of the area and hang around lures and go to high areas where there are a lot of stops seeing as that's where the good pokemon seem to spawn

**Comment by TheSavior** [comment]
Can you elaborate on what kinds of things would be in those python and yml files? I'm not sure I understand why every pokemon would have significantly different logic. The current understanding is that things like IV skills are the relevant piece but can be mostly generalized for all pokemon.

Also you should think about how your proposal fits in with the other proposal I made on using behavior trees: https://github.com/PokemonGoF/PokemonGo-Bot/issues/142

I believe the current feeling is that right now the priority is getting bugs fixed and small features added before doing any larger refactor since as you said, dev is changing really quickly.
