### ISSUE TITLE
Reset wake up location after sleep

### ISSUE THREAD

**Issue by nugrahawahyu** [PokemonGoF/PokemonGo-Bot#4901]
### Short Description
Add a new favorite location after wake up from sleep schedule.

**Comment by mjmadsen** [comment]
Similar to #3773 but I'd say distinctive. I swear we had something go through like this a while ago but I can't seem to find it right now.

**Comment by mjmadsen** [comment]
As mentioned about, similar to another. In thinking about this, I think we should account for the distance traveled, instead of going straight to the coords set. If the initial coords are so far away from our last coords, the delay should be adjusted. Ban trigger seems to be a function of time and distance, with some throttle limit set. 

To break it down a bit, there is obviously a speed between hatching and not. The only next trigger I know of is travelling too much too fast (teleportation). This seems to account for cars and planes. If it takes X hours to fly from Miami to LA, and you were there X-1hr, you get a softban.

**Comment by alexyaoyang** [comment]
I believe this can be done with `wake_up_at_location` now.
