### ISSUE TITLE
[Issue] Unable to read hatched egg details

### ISSUE THREAD

**Issue by pranavperfect** [PokemonGoF/PokemonGo-Bot#5158]
### Expected Behavior
Once egg hatches, it should be able to read what was the outcome.

### Actual Behavior
Displayed the entry but all values as error.

### Your FULL config.json (remove your username, password, gmapkey and any other private info)
Not applicable

### Output when issue occurred
[2016-09-03 18:56:28] [MainThread] [IncubateEggs] [INFO] [egg_hatched] {'candy': 'error', 'iv': 'error', 'stardust': 'error', 'exp': 'error', 'cp': 'error', 'pokemon': 'error'}

### Steps to Reproduce
Hatched a 10K egg

### Other Information
OS: 
Win 10
Branch: 
Master
Git Commit: 
ca94424f
Python Version: 
2.3.6

**Comment by pranavperfect** [comment]
After checking Pokemon GO app, it shows hatched Pokemon was Eevee.

**Comment by DeXtroTip** [comment]
Has that happened to any other egg?

**Comment by pranavperfect** [comment]
not that i recall. if perhaps we had an error log stored i would be able to tell. My bot runs generally 20 hours out of the day. so can't tell if this happened in the past or not.

**Comment by DeXtroTip** [comment]
Not sure why that happened, it should be working fine in that commit you're at. Last dev commit has some changes on IncubateEggs task and also add eggs hatched to db.

**Comment by Gobberwart** [comment]
This exact issue was fixed a few days ago, and was working correctly for me 22 hours ago:

[IncubateEggs] [INFO] [egg_hatched] Egg hatched with a Ekans (CP 450 - IV 10/14/15 0.87), 500 exp, 800 stardust and 10 candies.

That said, the way egg hatching is handled is as follows:

- Bot receives egg hatched info from server
- Bot sends inventory update request via api
- Bot searches updated inventory for details of the newly-hatched egg's pokemon
- Bot displays info

If the inventory doesn't update, then you'll see all "error" because there's no matching pokemon. Possibly this failed for some reason?
