### ISSUE TITLE
Can't find uncommon pokemon

### ISSUE THREAD

**Issue by iruy** [PokemonGoF/PokemonGo-Bot#5412]
### Expected Behavior
Find and catch uncommon pokemon

### Actual Behavior
When first starting my bot, I sometimes check Go Radar app, which recently told me of a Snorlax; I obtained the correct lat & long data and started the bot in that location, but it cannot find it. I also decreased the walk speed to 1-5 (min-max) but still nothing.
This same process works with pokemon like dratini, growlithe, Ivysaur, Wartortle (which are those I also tried the same "trick"). 

Is there any particular config to find uncommon pokemon?

**Comment by iruy** [comment]
I made some more test, and also tried increasing refresh cell rate (https://github.com/PokemonGoF/PokemonGo-Bot/issues/5409), but Snorlax is not found... Looks like an api issue?

**Comment by PokemonGoZ** [comment]
It could've been a fake Pokemon. These exist, because Niantic places uncommon and rare Pokemon on the server for scanners, maps, radars, etc to pick up, but they're actually not there. GoRadar retrieves information from users using te Jailbreak tweak Poke Go++. That tweak retrieves game data from the server. If you are playing, and see an uncommon or rare Pokemon show up on the side, tap it, and when it arrives at where the server said it was, it could've just been a bot lure.

**Comment by iruy** [comment]
Ok, thank you
