### ISSUE TITLE
 requirements.txt issue

### ISSUE THREAD

**Issue by ProZer0** [PokemonGoF/PokemonGo-Bot#5430]
Just tried to pull the latest update for the Master, then  pip2 install -r requirements.txt --upgrade , but the upgrade is stuck on the last line below, seems something wrong with the pgoapi repository.

$ pip2 install -r requirements.txt --upgrade
Requirement already up-to-date: numpy==1.11.0 in c:\bot3\pokemongo-bot\lib\site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: networkx==1.11 in c:\bot3\pokemongo-bot\lib\site-packages (from -r requirements.txt (line 2))
Obtaining pgoapi from git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi (from -r requirements.txt (line 3))
git clone in c:\bot3\pokemongo-bot\src\pgoapi exists with URL https://github.com/joelgreen/pgoapi.git/
The plan is to install the git repository https://github.com/pogodevorg/pgoapi.git/

**Comment by joelgreen** [comment]
`sudo pip install -r requirements.txt --upgrade`
If you're having trouble updating requirements try removing the -e in `requirements.txt`
`-e git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi`
to
`git+https://github.com/pogodevorg/pgoapi.git/@5e550f656b318227f021801c796b8a80ad917b93#egg=pgoapi`

You will also have to confirm to switch, and you may need to run it twice since pip has some issues with the repo cloning.

**Comment by ProZer0** [comment]
Thanks @joelgreen it worked as per your instructions
