### ISSUE TITLE
Implementation of PokeSnipers

### ISSUE THREAD

**Issue by bhoot1234567890** [PokemonGoF/PokemonGo-Bot#5458]
### Short Description
Use Sniping websites like pokemon https://pokesnipers.com/ | pokesniper.org/ | pokesnipe.de/ to find uncommon/rare pokemons.

### Possible solution
http://pokeapi.pokesnipe.de/ this site offers a json api that can be implemented. after going to location and encountering the pokemon(DON'T CATCH IT YET OR YOU'LL GET BANNED) return to the last stable location or your location before using sniper, and then catch it. using this method, one dosen't get banned.

### How it would help others
It would help in getting better "VIP" pokemons

**Comment by PokemonGoZ** [comment]
Currently maps.pikabot.org is working for me. It pulls locations of pokemon and you snipe them. It has a priority list in the config so it doesn't just snipe some Ratata in China. But yeah, this would be a cool implimentation, but I believe maps.pikabot.org is better (not because I'm biased towards PokamonGoF products) but because you can priority Charmander and it's evolutions if you want one to evolve or catch a Charizard and so on.

**Comment by Gobberwart** [comment]
pokesnipers (and other json type sites) are now supported by the new Sniper task. Closed.
