### ISSUE TITLE
The bot treats every Pokemon as a VIP

### ISSUE THREAD

**Issue by avexus** [PokemonGoF/PokemonGo-Bot#5521]
Windows 10 and Mac.

Master branch.

Normal conf file

**Comment by jmarenas** [comment]
While this issue is being fix, use this configuration in vips:
replace this:
`"any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },`
for this:
`"//any": {"catch_above_cp": 1200, "catch_above_iv": 0.9, "logic": "or" },`

There is something wrong with the last update, for now, you may not update so you will not have this issue.

**Comment by Gobberwart** [comment]
Fixed in dev. Wait until master is updated, or use dev branch instead.

**Comment by avexus** [comment]
@Gobberwart fixed in master right now.
