### ISSUE TITLE
[FR] Sniper task enhancement

### ISSUE THREAD

**Issue by kureijir** [PokemonGoF/PokemonGo-Bot#5568]
### Short Description
1. Add `min_ball` parameter to Sniper task
2. Add some kind of cooldown between snipes.

### How it would help others
(1): Without it we might run out of balls pretty fast. I think teleporting to a Dragonite with 5 pokeballs in bag is a bad idea. Old MoveToMapPokemon has this feature and I'm happy with it so far.
(2): I'm not sure about this, but when I first try Sniper task it spent over 5 minutes standing and sniping, no move, no fort spin. I don't know if this is bad though, except that it might make (1) happen faster :joy:

**Comment by YvesHenri** [comment]
I don't want to add anymore values to the config file. I'm trying to make it the simplest and cleanest as possible. The more flags the config has, the higher is the number of issues. I'm aware that sniping wastes A LOT of balls, but there's nothing you can do about it, not even customizing the number of balls in a config file. If you set this amount to 100, for example, and you currently have 110 balls, you might have a chance to snipe 1 to 3 times untill you go under 100 balls. Instead of 100, I have set a constant value of 10 (which might be increase to 25 or something). Sniping is supposed to hunt only very rare targets, like snorlaxes and dragonites, otherwise you'll constantly run out of balls, no matter what. Sniping too much is also dangerous, please bear in mind.

It has constant values for timeouts and they are:
Validating information: 7 seconds (theres a PR pending which will increase to 10 seconds)
Fetching information: 3 seconds
Landing after every teleport: 3 seconds
Teleporting to another target (if any): 3 seconds

There is, however, a bug with social mode that you would snipe forever. This is also going to be fixed in the PR I mentioned above.

**Comment by kureijir** [comment]
Okay, then please consider change that minimum balls value, 10 seems a bit low to me. 25 seems good.
