### ISSUE TITLE
lvl_up, poke_master, pokedex sample config or botConfig 

### ISSUE THREAD

**Issue by kokoye2007** [PokemonGoF/PokemonGo-Bot#5629]
### level_up / pokemon_master / pokedex base config.sample 
some body is need attack for Pokemon (prefer cp and iv), 
some body is need Pokedex all pokemon (sniper), 
some body is proud with Pokemon Trainer Level (xp), 
so basic config template for beginner (like me , foolish for easy config)

### Level up / Pokedex / Attack
level up for xp special config 
pokedex for sinper config - pokemap + sniper config
attack gym config - CP/IV higher sniper config
botConfig is need to update. we can add on botConfiguration tool.

### It's dream
who can support pokemon go bot ''dream come true''

**Comment by Anakin5** [comment]
in English ?

**Comment by kureijir** [comment]
Maybe I'm mistaken, but I think he wants 3 config example, one targets those who wants to level up as fast as possible, another targets those who wants his dex filled, and the last targets those who wants his Pokemon as strong as possible. I myself think this is unnecessary, since default config + sniping would achieve all those 3.

**Comment by Gobberwart** [comment]
Wouldn't be a bad idea, but I don't think we want to have to support/update any more example configs than we already have... Or do we?

**Comment by kokoye2007** [comment]
pokedex is like that #5638
