### ISSUE TITLE
why remove all sources of sniper, it still works?

### ISSUE THREAD

**Issue by desert0616** [PokemonGoF/PokemonGo-Bot#5650]
In order to config my own source, I try to remove all sources of the sniper to avoid any distraction on my debugging. But I found that even if I remove all sources of the sniper. It still works and can get some coordinates of Pokemon. Why? Does any predefined source exist?

Thanks.

**Comment by kolinkorr839** [comment]
When I removed all the sources in the sniper config, I get this message which means sniper will not be triggered at all.
```
[2016-09-24 11:02:29] [    Sniper] Validating sources: ...
[2016-09-24 11:02:29] [    Sniper] There is no source available. Disabling Sniper...
...
...
[2016-09-24 11:03:14] [    Sniper] Sniper was disabled for some reason. Scroll up to find out.
```

**Comment by NovaDev94** [comment]
@desert0616 From https://github.com/PokemonGoF/PokemonGo-Bot/blob/master/docs/configuration_files.md#sniper.  

The default configuration file has `mode = social` which means it will use the data from social network instead of specified urls. Try changing it to `mode = url` and see if it works with blank url list.

**Comment by Gobberwart** [comment]
Correct answer
