### ISSUE TITLE
feature new CP nerf/buff

### ISSUE THREAD

**Issue by MZorzy** [PokemonGoF/PokemonGo-Bot#5832]
So ni_ntic has changed CP base for all pokem. (only Lapras has no change)
https://www.reddit.com/r/pokemongodev/comments/5e6d5o/cp_buff_nerf_today/

need to update data/pokemon.json.
https://docs.google.com/spreadsheets/d/1HL5tKb1YVll2UMVlHsCFh7CcUKX6ctb55NFmnuEw660/edit#gid=0

**Comment by tihiniko** [comment]
I changed all the values, it seems to work
[updated pokemon stats.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/608541/updated.pokemon.stats.txt)

**Comment by MZorzy** [comment]
i try to add a pull request. #5836
tnx

**Comment by nachi9211** [comment]
@tihiniko 
I renamed this file then replaced data/pokemon.json and also web/data/pokemondata.json
But the assertion error still occurred, am I doing something wrong?

**Comment by tihiniko** [comment]
Jesus, I had the bug again, and found the mistake by me!
Eevee base defense was wrong, it is 127 in the file I made and it should be 121.
I did not find any other typos by me... I hope that was the only :+1: 
New txt
[updated pokemon stats.txt](https://github.com/PokemonGoF/PokemonGo-Bot/files/608936/updated.pokemon.stats.txt)

**Comment by nachi9211** [comment]
Working now (Y)

**Comment by MZorzy** [comment]
added to pull request

**Comment by vanbwodonk** [comment]
@nachi9211, how you make it worked again? I try to replace data/pokemon.json and web/data/pokemondata.json, still got same error.

**Comment by brenosoares** [comment]
my installation was work until yestarday. when i update the changes the bot stop working. i try with anothe account and still broken. sorry my english. but now my intallation does'nt work.

**Comment by nachi9211** [comment]
@vanbwodonk I am sorry, I just retried uncommenting the assert cp line and it fails again.
I think it best to wait till a finalized stats list has been published, I was referring to this http://pokemongohub.net/pokemon-go-new-max-cp-chart/
but wouldn't commit to it yet.
To make your bot work,

1) Comment out the assertion line <assert max(int(self.cp_exact), 10) == self.cp> in inventory.py.
2) You will also need to add <{"id":242,"name":"Transformacion","type":"Normal","damage":0,"duration":1230,"energy":7,"dps":0.0}> this to fast_moves.json
3) Add the move transformacion to Ditto's fast moves in Pokemon.json <,"Transformacion"> after Pound.

Also this will only work if you avoid the latest commit for checkin API version. Git reset to previous commit.
Sorry for the intermediary confusion, there seems to be some change since, 
Let me know if this still fails.
Remember, this will still trigger captcha checks, so only use this if you want to earn double candy from the event. Keep an eye on your device screen and reload when bot starts repeatedly restarting. This is no solution, but gets the bot working temporarily. Since the bot will crash anyway, give it a pause between frequent restarts to be safe.
