### ISSUE TITLE
TODO: New berries support

### ISSUE THREAD

**Issue by pogarek** [PokemonGoF/PokemonGo-Bot#5942]
Currently bot seems to use only Razz Berries. 
It would be good to enhance the functionality to use new berries, with controlled behavior (by config.json). 

Help appreciated.

**Comment by MeisterLLD** [comment]
I tried a very brutal idea.
In catch_pokemon_worker.py, replaced the 

> ITEM_RAZZBERRY = 701

by 

> ITEM_RAZZBERRY = 705

to try and have the bot us Pinap as if it were using Razz. Encountered a VIP mon and it tried to throw it but answered 

> Unknown response when throwing berry

I then opened the real game myself and indeed, only 3 candies were gotten instead of 6. So I guess the bot didn't really succeed at throwing the Pinap.
So the changes will probably be more subtle than that :)

**Comment by MerlionRock** [comment]
I'm working on it right now.

**Comment by MerlionRock** [comment]
Closing it. Merged :)

**Comment by pogarek** [comment]
:-)
