### ISSUE TITLE
After re-login from stale session, bot teleports to random pokestop

### ISSUE THREAD

**Issue by Nurvx** [PokemonGoF/PokemonGo-Bot#854]
### Expected Behavior
Expected the bot to pick up right where it left off (location) after a successful re-login

### Actual Behavior
Teleported trainer to a distant pokestop (see smooth line in screenshot)

### Steps to Reproduce
Run bot till session is stale and re-logs in.  Then look at the web map (submodule)

### Other Information
OS: 

Mac

<img width="645" alt="screen shot 2016-07-25 at 3 13 08 pm" src="https://cloud.githubusercontent.com/assets/6528118/17113971/e319963a-527a-11e6-9905-7b27d3716be0.png">

Git Commit: (run 'git log -n 1 --pretty=format:"%H"' and paste it here)

**Comment by bimahp** [comment]
how can i show that red line route on my map to confirm this?

**Comment by Nurvx** [comment]
On the right hand side, click "Settings", then toggle "Bot Path" on

**Comment by surfaace** [comment]
successful re-login, we should use location cache, and not pick a new location

**Comment by surfaace** [comment]
tagging #810 as both reference last location cache

**Comment by MikeDX** [comment]
This is (probably) due to the self.position (or self.location) not being updated correctly when walking. There are multiple instances in the codebase where position is changed but self.position is not updated - so when the session is due to expire, the position used is from the last time self.position was updated, which could be any time!
